### PR TITLE
Patch Solr Dist Search - No Stale Check or Nagle

### PR DESCRIPTION
**Pull request by rzezeski**
A few weeks ago while benchmarking Yokozuna I found that latency was much higher than I would have expected.  After much investigation I discovered that the Apache HTTP Client (which Solr uses for distributed search) stale check is a large contributor.
- Write an HTTP client for dist search up to spec with the HTTP client version being used.  I noticed currently some deprecated calls are being made.
- Disable the stale check.
- Disable nagle.  The packets being sent aren't small so no need to bother with nagle.
- Change yokozuna build to pull Solr 4.0 source and apply patch files.
- Post benchmarks proving improvement.
- Once settled, send patch to Solr mailing list and jira.

### CODE REVIEW

**Comment by rzezeski** [comment]
This PR produces a 2-4x (depending on the query) increase in throughput on my home cluster.
- Disabled stale check and nagle.
- Added background task to evict idle conns from conn pool to avoid IOExceptions.
- Based on Solr 4.1 since we have since upgraded.
- Not sure if this is an ideal patch for upstream, but should mention something on the mailing list with a link to this PR to open discussion.

**Comment by rzezeski** [comment]
## Alpha (Before)

summary

## Alpha (After)

summary

## Alpha (Riak Search)

summary

**Comment by rzezeski** [comment]
## Beta (Before)

summary

## Beta (After)

summary

## Beta (Riak Search)

summary

**Comment by rzezeski** [comment]
## Charlie (Before)

summary

## Charlie (After)

summary

## Charlie (Riak Search)

summary

**Comment by rzezeski** [comment]
## Delta (Before)

summary

## Delta (After)

summary

## Delta (Riak Search)

summary

**Comment by rzezeski** [comment]
## Echo (Before)

summary

## Echo (After)

summary

## Echo (Riak Search)

summary

**Comment by rzezeski** [comment]
## Echo (Before)

summary

## Echo (After)

summary

## Echo (Riak Search)

summary

**Comment by rzezeski** [comment]
## Foxtrot (Before)

summary

## Foxtrot (After)

summary

## Foxtrot (Riak Search)

summary

**Comment by rzezeski** [comment]
## Golf (Before)

summary

## Golf (After)

summary

## Golf (Riak Search)

summary

**Comment by rzezeski** [comment]
## Hotel (Before)

summary

## Hotel (After)

summary

## Hotel (Riak Search)

summary

**Comment by rzezeski** [comment]
## India (Before)

summary

## India (After)

summary

## India (Riak Search)

summary

**Comment by rzezeski** [comment]
## Juliet (Before)

summary

## Juliet (After)

summary

## Juliet (Riak Search)

summary

**Comment by rzezeski** [comment]
## Kilo (Before)

summary

## Kilo (After)

summary

## Kilo (Riak Search)

summary

**Comment by rzezeski** [comment]
## Lima (Before)

summary

## Lima (After)

summary

## Lima (Riak Search)

summary

**Comment by rzezeski** [comment]
I just remembered that in all these benchmarks I set Solr's logging level to `WARNING`.

**Comment by coderoshi** [comment]
Everything looks to be in order. Works as advertised. Benchmarked to hell. :+1:

**Pull request merged**
