### PR TITLE
Download custom jars from s3

### PR DESCRIPTION
**Pull request by rzezeski**
This should address #314. See that PR or commit msgs for more info.

In order to test this you should run `make clean && rm -rf deps` to make sure you get latest. You'll also want to wipe out your verify dir.

### CODE REVIEW

**Comment by bowrocker** [comment]
Works for me: https://gist.github.com/bowrocker/9117066

Subsequent compiles without 'make clean' do not download them again. This is a good thing, but what happens if the jars change? Do we have to remember to do a clean to update? If so, perhaps a follow on is to check and track a checksum, and download only if it changes?

**Comment by rzezeski** [comment]
Actually they should be downloaded again after clean because the files are not cached like the custom Solr package. They are small so hopefully that is fine for now.

The jar are versioned and the only way they change is if the scripts are updated to a new version. To get the new jars you'll want to run a make clean followed by make.

**Comment by bowrocker** [comment]
Makes sense to me, just checking. Things like that have bitten me in the past.

I am :+1:

**Comment by rzezeski** [comment]
Yea this is why I added the version. The yokozuna-1.jar will never change. If we add or modify handlers that will require the following steps:
1. Build yokozuna-2.jar.
2. Upload to s3.
3. Set `YZ_JAR_VSN=2` in `grab-solr.sh`.

**Pull request merged**
