### PR TITLE
Use .jar files in priv/ not data/yz/

### PR DESCRIPTION
**Pull request by beerriot**
It seems like a bad idea to use .jar files out of the data directory. Instead, let's use them from YZ's `priv/` directory, where they will be versioned with the YZ release. This PR does this, while also cleaning things out of `priv/` that we don't want to ship in the release (source files, build scripts, etc.).

This PR requires that you use a PR in the riak repo as well: basho/riak#366

There was quite a bit of hit & miss in getting this "right". I tried to leave notes about why things changed after I figured out how to change them, but I'm sure I missed some. So, if some change seems random and/or unnecessary, please ask.

Solr is now unpackaged/built in the `build/` directory, instead of `priv/`. We don't want all of that accompanying the release, so we just copy in what we need.

This PR also includes a change to how the JVM decides when to tear itself down after Erlang has quit (it now waits for a read from stdin to return an error, instead of periodically running a bash script to check the owner of the JVM process). This was included in order to avoid the work of correcting the path to `monitor.sh`.

Things I'm not 100% happy with:
- It seems like `priv/conf/` shouldn't need to exists, and that `data/yz/_yz_default` should be good enough … but I see errors if I remove it.
- I moved `log4j.properties` to the node's `etc/` directory, because it seemed like config a user might want/need exposed. The way the path to this file is generated, and the generated path the file contains, seems fragile, though.
- We should probably be creating everything in `data/yz` at startup time, if it doesn't exist. That would allow the user to blow away testing data at any time, as well as easily reconfigure where data is stored without moving files.
- Jetty is still spraying the contents of `solr.war` onto disk. When I set `extractWAR` to `false` in the context xml, it spewed errors in the log instead. We may have to just figure out a safe place for Jetty to do this, instead of insisting that it not do so. Sidenote: in source-rel builds, the spew happens in `rel/riak/solr-webapp`, but in actual packaged builds it may happen in `/tmp`.

Things I haven't tested:
- ~~I haven't run the entirety of `verify.sh` on this setup yet.~~
- I haven't used the non-prepackaged branches of the `grab-solr.sh` script.

### CODE REVIEW

**Comment by coderoshi** [comment]
I ran into a couple issues:
- Before checking the branch you have to `rm priv/solr/etc/jetty.xml`
- `make stagedevrel` fails executing overlay, claiming `enoent`, annoyingly, because `vars/dev1_vars.config` does exist

**Comment by beerriot** [comment]
> - Before checking the branch you have to `rm priv/solr/etc/jetty.xml`

Ah, yes, you will have to in order to make git happy. I moved `jetty.xml` from `priv/` to `priv/solr/etc/`, where it is supposed to live. One of the scripts used to copy it there during the build, but there is no reason to do that (see 2f1fc9b). 

> - `make stagedevrel` fails executing overlay, claiming `enoent`, annoyingly, because `vars/dev1_vars.config` does exist

From a fresh checkout of `riak`, plus a modification of `rebar.config` to point to this `yokozuna` branch, I did not have this problem. Each `vars/dev*_vars.config` file is generated by the `dev%` make target, a dependency of the `stagedev%` target, which are generated dependencies of the `stagedevrel` target, in the Makefile I'm looking at.

**Comment by beerriot** [comment]
Tests pass a clean checkout.

```
kettle:tools bryan$ ./verify.sh --yz-branch bwf-move-jars --riak-branch bwf-move-jars /Users/bryan/rtyz | tee verify.out
...snip...
Test Results:
yz_wm_extract_test-bitcask : pass
yz_siblings-bitcask        : pass
yz_schema_admin-bitcask    : pass
yz_pb-bitcask              : pass
yz_monitor_solr-bitcask    : pass
yz_mapreduce-bitcask       : pass
yz_languages-bitcask       : pass
yz_index_admin-bitcask     : pass
yz_flag_transitions-bitcask: pass
yz_fallback-bitcask        : pass
yz_errors-bitcask          : pass
yokozuna_essential-bitcask : pass
---------------------------------------------
0 Tests Failed
12 Tests Passed
That's 100.0% for those keeping score
~/rtyz
INFO: IF YOU ARE READING THIS THEN I THINK THINGS WORKED
```

**Comment by rzezeski** [comment]
> I haven't used the non-prepackaged branches of the grab-solr.sh script.

Don't worry about that.  Yokozuna should only ever grab a pre-packaged Solr from now on.  The rest of that cruft can eventually be removed.

**Comment by rzezeski** [comment]
@coderoshi Any chance you didn't pass `--riak-branch` or `--riak-source`?  I just had successful run of `yokozuna_essential`, going to run full suite now.  Here's my invocation:

```
./verify.sh --yz-source ~/work/yz-bf-jars --riak-branch bwf-move-jars --test yokozuna_essential /spinning/yz-bwf-verify | tee verify-bwf.out
```

**Comment by rzezeski** [comment]
Tests pass for me

```
$ ./verify.sh --yz-source ~/work/yz-bf-jars --riak-branch bwf-move-jars /spinning/yz-bwf-verify | tee verify-bwf-all.out
...
Test Results:
16:20:29.990 [info] Stopped Node... /spinning/yz-bwf-verify/rt/riak_yz/dev/dev5/bin/riak stop ~ wasn't running.
yz_wm_extract_test-bitcask : pass
yz_siblings-bitcask        : pass
yz_schema_admin-bitcask    : pass
yz_pb-bitcask              : pass
yz_monitor_solr-bitcask    : pass
yz_mapreduce-bitcask       : pass
yz_languages-bitcask       : pass
yz_index_admin-bitcask     : pass
yz_flag_transitions-bitcask: pass
yz_fallback-bitcask        : pass
yz_errors-bitcask          : pass
yokozuna_essential-bitcask : pass
---------------------------------------------
0 Tests Failed
12 Tests Passed
That's 100.0% for those keeping score
/spinning/yz-bwf-verify
INFO: IF YOU ARE READING THIS THEN I THINK THINGS WORKED
```

**Comment by coderoshi** [comment]
I can get the verify.sh script to work. What I can't get to work is executing `make stagedevrel` in riak with this branch

**Comment by rzezeski** [comment]
I was able to build a stagedevrel:

```
git clone -b bwf-move-jars git@github.com:basho/riak.git riak_yz-bwf-move-jars
cd riak_yz-bwf-move-jars
sed '/{yokozuna,/,/}}}/{s/{branch, "master"}/{branch, "bwf-move-jars"}/;}' -i.bk rebar.config
make
make stagedevrel
```

**Comment by coderoshi** [comment]
crazy, those steps don't work for me. Anyway, we all got verify working, and you both got stagedevrel working, so I'm cool with a +1

**Comment by hazen** [comment]
I'm trying to independently verify @rzezeski's steps, too, but over MiFi cloning the universe is taking a while.  Details at 11.

**Comment by hazen** [comment]
And `make stagedevrel` works for me, too.  +1 again

**Comment by rzezeski** [comment]
@coderoshi must be building in the Terah cloud again.

@beerriot +1 to merge

**Comment by hazen** [comment]
FWIW at this late hour, my verify.sh mewstly passed:

```
Test Results:
15:57:55.856 [info] Stopped Node... /tmp/yz-verify/rt/riak_yz/dev/dev5/bin/riak stop ~ wasn't running.
yz_wm_extract_test-bitcask : pass
yz_siblings-bitcask        : pass
yz_schema_admin-bitcask    : pass
yz_pb-bitcask              : pass
yz_monitor_solr-bitcask    : pass
yz_mapreduce-bitcask       : pass
yz_languages-bitcask       : pass
yz_index_admin-bitcask     : pass
yz_flag_transitions-bitcask: fail
yz_fallback-bitcask        : pass
yz_errors-bitcask          : pass
yokozuna_essential-bitcask : pass
---------------------------------------------
1 Tests Failed
11 Tests Passed
That's 91.66666666666666% for those keeping score
/tmp/yz-verify
INFO: IF YOU ARE READING THIS THEN I THINK THINGS WORKED
```

**Comment by rzezeski** [comment]
@beerriot I noticed that there was a merge conflict related to some recent rebar.config changes I made.  I went ahead and merged master and resolved them.  I verified that a build from scratch still works.  No need to re-run verify.

**Pull request merged**
