### PR TITLE
Bugfix/zl/entropydata v3 update tests for commit

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
- upgrade tests to use softautocommit
- better decoding
- script/version upgrade for entropydata jar

### CODE REVIEW

**Comment by fadushin** [comment]
Verified all yz tests through r_t, and manually verified performance improvement in loaded cluster.

+1 16825f0

**Comment by fadushin** [comment]
come on, bors...

+1 16825f0

**Comment by zeeshanlakhani** [comment]
@fadushin glad bors was dead... i needed to add a commit :). Mind "reviewing" again?

**Comment by zeeshanlakhani** [comment]
trying bors again:

:+1: 50ebdedd0c169d4bb00bb601bf5685dc15125950

**Comment by zeeshanlakhani** [comment]
https://github.com/basho/riak_test/pull/859 will fail until this is merged in.. when bors says okiez.

**Comment by jonmeredith** [comment]
+1 50ebdedd0c169d4bb00bb601bf5685dc15125950

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Pull request merged**
