### PR TITLE
tools.mk update and dialyzer fixes

### PR DESCRIPTION
**Pull request by reiddraper**

### CODE REVIEW

**Comment by reiddraper** [comment]
There are a couple of outstanding errors left, one of the most interesting is with the `tree()` type, which include says should be a `pid()`, but inside `riak_kv_index_hashtree:get_build_time/1`, it expects a record, or something. Worth investigating.

**Comment by coderoshi** [comment]
+1 Along with #327, dialyzer is happy, the changes look good

**Comment by reiddraper** [comment]
_I'm going to push another commit to update tools.mk, so please avoid merging until then._

**Comment by Vagabond** [comment]
I updated tools.mk to fix another bug we found in tools.mk.

**Comment by reiddraper** [comment]
+1

**Pull request merged**
