### PR TITLE
add wait_for function to check on search results in yz_pb, *soft-commit...

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
...s should be 1100

### CODE REVIEW

**Comment by bearcage** [comment]
Changes look good to me, and it passes 10x locally on both tests. +1 5fb4d97

**Comment by bearcage** [comment]
+1 5fb4d97

**Comment by bearcage** [comment]
@borshop y u no like me anymore?

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Comment by bashopatricia** [comment]
@zeeshanlakhani Appears merged into develop. Should this be going into the 2.1 branch?  Please forgive me if I am looking at this wrong. Learning GH.

**Comment by Basho-JIRA** [comment]
Sent note to Zeeshan about whether this needs to get in 2.1 branch. Looks like it went to develop in April.  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by zeeshanlakhani** [comment]
@bashopatricia I'm pretty sure this is already covered in the maint branches for 2.0/2.1.

**Comment by bashopatricia** [comment]
OK thanks.

**Pull request merged**
