### PR TITLE
Yokozuna RHS sub schema update

### PR DESCRIPTION
**Pull request by joedevivo**
Requires:
- [x] Eng +1
- [x] CSE +1
- [x] ProdMgmt +1

### CODE REVIEW

**Comment by coderoshi** [comment]
+1 `17 Tests Passed`

**Comment by gburd** [comment]
Why "yolo" for a directory name rather than "search" or "solr" or something a bit more descriptive?

**Comment by joedevivo** [comment]
@gburd it's just a unit test. doesn't matter what it is, so much as the assertion passes :)

**Comment by gburd** [comment]
PM +1

**Comment by jmshoffs0812** [comment]
CSE +1

**Pull request merged**
