### PR TITLE
Fixes calls into security

### PR DESCRIPTION
**Pull request by lordnull**
Without these, the yz_security riak_test is unable to pass.

### CODE REVIEW

**Comment by jonmeredith** [comment]
Are the end user commands case sensitive?

**Comment by rzezeski** [comment]
> Are the end user commands case sensitive?

Good question. I was under the impression we recently patched security so that is is case _insensitive_. Why does the test fail if uppercase is used?

**Comment by lordnull** [comment]
Seems it is case sensitive; using the command-line script, grant fails if the "on" or "to" have capitals.

**Comment by rzezeski** [comment]
> Seems it is case sensitive; using the command-line script, grant fails if the "on" or "to" have capitals.

Perhaps it was changed from upper to lower and I misread it as case insensitive. IIRC @macintux did the work?

**Comment by macintux** [comment]
Sorry I didn't dig for code that uses this command, mea culpa.

Correct, the code is case-sensitive (like all of our riak-admin commands that I can tell) and I changed it from all-upper to all-lower.

**Comment by rzezeski** [comment]
+1 3eba618

```
Test Results:
yz_security-bitcask: pass
---------------------------------------------
0 Tests Failed
1 Tests Passed
```

**Comment by rzezeski** [comment]
@borshop merge

**Pull request merged**
