### PR TITLE
Make YZ_BENCH_DIR environment variable optional

### PR DESCRIPTION
**Pull request by hazen**
Instead you can use `{rt_bench_path, ["/tmp/yz-verify/yokozuna/misc/bench"]},` in your .riak_test.config so Giddyup can actually run the tests.

### CODE REVIEW

**Comment by rzezeski** [comment]
Isn't `rt_bench_path` already used by other tests? I imagine this would point to something like `~/work/basho_bench`.  If that is the case then this change probably won't play well with other riak tests run by giddy up because `YZ_BENCH_DIR` points to something like `~/work/yokozuna/misc/bench`.

Perhaps the real fix, to make this less confusing, is to use the `rt_bench_path` to actually call the `basho_bench` command but use `YZ_BENCHR_DIR`, with `yz_bench_dir` as backup, as a path to add to the `code_paths` in the generated basho bench config.

The entire point of this env var is so that the `yz_driver` module can be found.  Using the `basho_bench` command under `deps/basho_bench` just happened to be convenient when I wrote the first yokozuna riak test over a year ago.

**Comment by rzezeski** [comment]
Maybe even better is just get rid of YZ_BENCH_DIR completely, and add add a config `yz_dir`.  Then we can use `rt_config:get(yz_dir)` and have access to any files in Yokozuna that are helpful for testing.

**Comment by hazen** [comment]
@rzezeski I created `rt_bench_path`, so it's unique unless I happened to reinvent the name.

I was asking the other day about the need for YZ_BENCH_DIR at all.  It would certainly be cleaner if we just went with a single RT config parameter.  `yz_dir` sounds like a great name.

Did I interpret your last comment correctly?  Nuke YZ_BENCH_DIR?

**Comment by rzezeski** [comment]
Yea, go ahead and nude the env var `YZ_BENCH_DIR` for now.  Let's see if we can get by with just a `yz_dir` rt config.

**Comment by rzezeski** [comment]
LOL at "nude".  Nuke!  I meant nuke!

**Comment by hazen** [comment]
LOL! Typing? How do you type? Must be my naked finger memory.

OK, so should I add a second config parameter just for basho_bench?  Or actually build it in the test code?

```
YZBenchDir = rt_config:get(yz_dir) ++ "/misc/bench"
```

I guess I could define the `yz_bench_dir` off of `yz_dir` and do something like this:

```
YZBenchDir = rt_config:get(yz_dir) ++ rt_config:get(yz_bench_dir)
```

where `yz_bench_dir` is just a subdirectory.

**Comment by rzezeski** [comment]
Just build it all off `yz_dir` for now.

**Comment by rzezeski** [comment]
+1 to merge

**Comment by rzezeski** [comment]
Related to #132

**Pull request merged**
