### PR TITLE
Enable setting Jetty temp directory [JIRA: RIAK-1787]

### PR DESCRIPTION
**Pull request by lukebakken**
This change allows a user to use the `search.temp_dir` configuration variable to set the temp directory used by Jetty.

See the following issues:
- basho/yokozuna#401
- basho/node_package#150

This is somewhat important as the default causes Solr to write data in directories that shouldn't be written to, like `/usr/local/lib/riak/lib/yokozuna-2.0.0beta1-81-g47214a6/priv/solr` on FreeBSD.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Did this get lost for 2.0?

**Comment by zeeshanlakhani** [comment]
@lukebakken is this something you want to update... and I can take a look at and run tests against?

**Comment by lukebakken** [comment]
Hopefully I'll have time next week!

**Comment by zeeshanlakhani** [comment]
@lukebakken cool.

**Comment by lukebakken** [comment]
@zeeshanlakhani - latest develop merged in.

**Comment by lukebakken** [comment]
@zeeshanlakhani - develop merged in again.

**Comment by zeeshanlakhani** [comment]
thanks @lukebakken... i'll try to catch up on this later this week.

**Comment by seancribbs** [comment]
@lukebakken Does this need to go in 2.1.1/2.0.6?

**Comment by zeeshanlakhani** [comment]
It should... Yep :). I asked Fred to review/test.

Zeeshan Lakhani
programmer | 
software engineer at @basho | 
org. member/founder of @papers_we_love |
twitter => @zeeshanlakhani

**Comment by bashopatricia** [comment]
Sean - I can create a JIRA for this and put in both releases, unless you
know one is already there.  I was unable to find an existing JIRA with a
quick search.

Patti

On Wed, Apr 29, 2015 at 7:00 AM, Zeeshan Lakhani notifications@github.com
wrote:

> It should... Yep :). I asked Fred to review/test.
> 
> Zeeshan Lakhani
> programmer |
> software engineer at @basho |
> org. member/founder of @papers_we_love |
> twitter => @zeeshanlakhani
> 
> > On Apr 29, 2015, at 9:39 AM, Sean Cribbs notifications@github.com
> > wrote:
> > 
> > @lukebakken Does this need to go in 2.1.1/2.0.6?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/yokozuna/pull/413#issuecomment-97435262.

## 

_Patricia Brewer_
Skype: pbrewer77
Sr Program Manager
Basho Technologies, Reno

**Comment by seancribbs** [comment]
@bashopatricia I was unable to find it as well. Please do create one and attach the labels appropriately

**Comment by bashopatricia** [comment]
@seancribbs I assigned the JIRA 1787 to Fred Dustin based on GH conversation.  Let me know if you find I setup anything incorrectly.  Thanks!

**Comment by fadushin** [comment]
+1 e316f51

**Pull request merged**
