### PR TITLE
Still need to support Erlang 15B

### PR DESCRIPTION
**Pull request by rzezeski**
For the time being Yokozuna still needs to compile on 15B and cannot
use the new BIFs.

Pinging @jaredmorrow and @coderoshi

### CODE REVIEW

**Comment by hazen** [comment]
Builds successfully under R15B03, now checking verify.sh...

**Comment by coderoshi** [comment]
+1 It works. Ship it

**Comment by hazen** [comment]
FWIW, several verify.sh failures against pre4

```
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration-bitcask      : fail
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_flag_transitions-bitcask  : fail
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yokozuna_essential-bitcask   : fail
aae_test-bitcask             : fail
---------------------------------------------
4 Tests Failed
12 Tests Passed
That's 75.0% for those keeping score
```

**Comment by rzezeski** [comment]
Hmmm, `flag_transitions` is going away so I don't care about that one. `rs_migration` is known breakage. But the last two is not cool. I'll try running on my end. I doubt it's related to this patch but doesn't mean there isn't something wrong. I thought I saw indefinite AAE again the other day running a demo.

**Comment by rzezeski** [comment]
These pass for me. There are still issues around cluster building that are not related to Yokozuna. That could be what you hit. I'm going to merge.

**Pull request merged**
