### PR TITLE
OTP20

### PR DESCRIPTION
**Pull request by llelf**

### CODE REVIEW

**Comment by llelf** [comment]
base branch? `develop-3.0`?

/cc @martinsumner

**Comment by llelf** [comment]
- [x] travis
- [x] riak_kv to be merged
- [x] riak_test_compile ? FIXME

**Comment by martincox** [comment]
Won't compile as the changes in riak_pb (from erlang protobuffs to gpb) requires the messages to be in camel case. It pulls riak-erlang-client (non updated riak_pb) before riak_kv (with develop-3.0 riak_api), so it can't compile as the record names are different due to the pb changes.

See here: https://github.com/basho/riak_pb/commit/bf5449e1f660c83041c73387b4a090e8b92da6c1

**Comment by martincox** [comment]
I guess next on our list is riak-erlang-client

**Comment by llelf** [comment]
> Won't compile as the changes in riak_pb (from erlang protobuffs to gpb)

@martincox Wait.   So no more [pokémons](https://github.com/basho/erlang_protobuffs/blob/master/src/pokemon_pb.erl#L44)?
That's really bad timing considering the upcoming [movie](https://en.wikipedia.org/wiki/Pokémon:_Detective_Pikachu).

**Comment by martincox** [comment]
ahaha, thought that was an obscure reference until I clicked the link! ><

**Comment by martincox** [comment]
Gotta catch em all... (compilation errors).

**Comment by llelf** [comment]
gpc changes pushed.

But there's still a mismatch, as this branch assumes some things from riak_kv’s develop that are not in riak_kv’s develop-3.0 (e. g. https://github.com/basho/riak_kv/commit/32bcff513d92e228facd471cc2313a2623b1269d for b71590608fc8b1950c19a824fc88ed498bf41c2b).

And then `riakc`.

**Comment by llelf** [comment]
> But there's still a mismatch, as this branch assumes some things from riak_kv’s develop that are not in riak_kv’s develop-3.0 (e. g. basho/riak_kv@32bcff5 for b715906).

alright, since develop is not going to be merged,
develop-3.0 should point to a14d4001bf6011d0cfec46c67abbd96f651f65de aka 2.1.10-226 aka develop-2.2, right?

**Comment by martincox** [comment]
@llelf re-created develop-3.0 so it's branched from develop-2.2.

**Comment by llelf** [comment]
rebased

**Comment by martincox** [comment]
I think update the ibrowse version to v4.4.0 and it's good to go. :+1:

**Comment by llelf** [comment]
@martincox done

**Pull request merged**
