### PR TITLE
Add test to ensure default extractor map is sorted

### PR DESCRIPTION
**Pull request by lukebakken**
See #666 (RIAK-1480) (RIAK-2190) which has only been merged to `2.0`. Opening this PR due to issues raised in #699 (RIAK-1867)

### CODE REVIEW

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by JeetKunDoug** [comment]
thumbot retry

**Comment by JeetKunDoug** [comment]
@lukebakken can you get this rebased onto `develop` please? Would like to get it merged.

**Comment by davidx** [comment]
thumbot retry

**Comment by lukebakken** [comment]
@JeetKunDoug - all set, I had hoped that this would be merged for 2.2 ... then forgot about it 😸

**Comment by lukebakken** [comment]
@JeetKunDoug @davidx - I have no idea why tests are failing. They're fine on Travis CI and local on my workstation ... though those two aren't the result of a merge to `develop`. I'll look at it in an hour or so.

**Comment by lukebakken** [comment]
@JeetKunDoug - something to do with quickcheck, which I don't have available. I doubt this is due to the changes in the PR. Let me know if you can look at it:

```
yz_index_hashtree_eqc: index_hashtree_test_ (module 'yz_index_hashtree_eqc')...08:07:40.812 [info] Application lager started on node nonode@nohost
*failed*
in function eqc:quickcheck/1 (../src/eqc.erl, line 1275)
in call from yz_index_hashtree_eqc:'-index_hashtree_test_/0-fun-1-'/0 (test/yz_index_hashtree_eqc.erl, line 72)
**exit:{noproc,{gen_server,call,
                    [riak_core_capability,
                     {register,{riak_kv,object_hash_version},
                               {capability,[0,legacy],legacy,undefined}},
                     infinity]}}
  output:<<"Starting Quviq QuickCheck version 1.36.1
   (compiled at {{2015,9,11},{11,37,51}})
Licence for Basho (CI until May 2017) reserved until {{2016,12,7},{8,15,29}}
">>

08:07:41.049 [error] CRASH REPORT Process <0.1388.0> with 4 neighbours exited with reason: no such process or port in call to gen_server:call(riak_core_capability, {register,{riak_kv,object_hash_version},{capability,[0,legacy],legacy,undefined}}, infinity) in gen_server:init_it/6 line 328
08:07:41.050 [error] CRASH REPORT Process riak_core_ring_events with 0 neighbours exited with reason: no such process or port in call to gen_server:call(riak_core_capability, {register,{riak_kv,object_hash_version},{capability,[0,legacy],legacy,undefined}}, infinity) in gen_event:terminate_server/4 line 320
```

**Pull request closed without merging**
