### PR TITLE
Change `/search/Index` to `/search/query/Index`

### LINKED ISSUE #383: Ambiguous HTTP resource
If a user creates the and index named `index` then they will not be
able to query it via HTTP because the `/search/index` resource is
being used by `yz_wm_index`.  The two solutions I see are:
1. Disallow an index named `index`.
2. Move the `yz_wm_search` route to `/search/query/IndexName`.

I think the second is cleaner and more consistent.  Though I'm sure
it's not very RESTful (I admit I don't understand how to make good
HTTP APIs).  In any case something has to be done and option (1) seems
like a poor choice.

ping: @coderoshi @seancribbs

### PR DESCRIPTION
**Pull request by rzezeski**
Fixes #383.

The routes for querying and index administration are ambiguous if
there is an index named `index`.  The user will not be able to query
because Yokozuna will interpret `GET /search/index?q=...` as a request
to the index admin resource.  This commit changes the query resource
to `/search/query/Index` so there is no ambiguity.

### CODE REVIEW

**Comment by rzezeski** [comment]
Docs updated in basho/basho_docs#1117.

**Comment by coderoshi** [comment]
- [x] compile/unit test
- [x] riak test
- [x] dialyzer
- [x] documented

```
Test Results:
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : pass
yz_ring_resizing-bitcask     : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
0 Tests Failed
18 Tests Passed
That's 100.0% for those keeping score
```

**Comment by coderoshi** [comment]
+1 c248012

**Comment by rzezeski** [comment]
@borshop merge

**Pull request merged**
