### PR TITLE
fix regression

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
This will fix/handle failing tests
- yz_index_admin
- yz_schema_admin

### CODE REVIEW

**Comment by fadushin** [comment]
Lowers the timeout to 45 secs on server side, and includes the same behavior as in the pb server for recognizing a timeout configured in advanced config.

+1 ccff826

**Comment by cmeiklejohn** [comment]
`yz_index_admin` is still failing for me.

```
17:06:06.011 [warning] yz_index_admin failed: {{badmatch,{error,req_timedout}},[{yz_index_admin,confirm_create_index_bad_schema,1,[{file,"riak_test/yz_index_admin.erl"},{line,238}]},{yz_index_admin,confirm,0,[{file,"riak_test/yz_index_admin.erl"},{line,145}]},{riak_test_runner,return_to_exit,3,[{file,"src/riak_test_runner.erl"},{line,159}]}]}
```

**Comment by cmeiklejohn** [comment]
Recloned, rebuild yokozuna with this branch, rebuilt devrel and this still fails.

**Comment by zeeshanlakhani** [comment]
Hmm. @fadushin and I get this to pass continuously. It still may be a race. Change https://github.com/basho/yokozuna/pull/515/files#diff-1a3790bb249991466837d81c6fa805d1L133 to the original default, `30000`, and let me know.

**Comment by cmeiklejohn** [comment]
:+1: c903f78

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
@borshop merge

**Pull request merged**
