### PR TITLE
Fix some dialyzer errors in yz_dt_extractor.

### PR DESCRIPTION
**Pull request by seancribbs**
Found by @rzezeski in #250.

### CODE REVIEW

**Comment by hazen** [comment]
No sign of the dialyzer errors which were found in #250 

```
102c102
< ==> before (compile)
---
> ==> after (compile)
131,132d130
< yz_dt_extractor.erl:93: The variable Err can never match since previous clauses completely covered the type #state{}
< yz_dt_extractor.erl:99: The call yz_dt_extractor:extract_map(Name::binary()) breaks the contract (field_path_name()) -> fun(({{binary(),module()},term()},state()) -> state())
```

:+1:

**Comment by seancribbs** [comment]
@javajolt You got your dialyzer woes solved?

**Comment by hazen** [comment]
yup

**Comment by seancribbs** [comment]
Thanks for the review!

**Comment by hazen** [comment]
Thanks for the help!

**Pull request merged**
