### PR TITLE
cherry-pick hashtree update for hotfix.

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
- add idx_hashtree code that went into origin/2.0 from PR #578. 
- Need to also test against commit 815288df2239fef40722d0bd7025d840ffd05691, as that's the commit before the batching/queue code, i.e. https://github.com/basho/yokozuna/compare/815288df2239fef40722d0bd7025d840ffd05691...hotfix/2.0.6-2012.08.25. From looking at the diff, this will be correct and fixes the list:last issue as well, which is in the pre-batching/queue code. 

(cherry picked from commit d95a2881948d26c7e451091e36098df36eff8116)

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
Ran tests against https://github.com/basho/yokozuna/tree/hotfix/2.0.6-2012.08.25-815288d-to-d95a288, which is the hashtree work atop pre-batching/queue work, and all tests pass except for yz_search_http, which is not part of this hotfix.

**Comment by fadushin** [comment]
Verified all riak_tests pass with these changes, as well as the associated changes in riak_core and riak_kv.

**Comment by fadushin** [comment]
+1 83052d5

**Comment by fadushin** [comment]
@borshop merge

**Pull request merged**
