### PR TITLE
Backport/zl/merge develop into 2.1

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
Ok @JeetKunDoug, @fadushin. Bringing _develop_ into 2.1 (always forget to change the base in PR's... grrr! :tiger:). 

This now also includes the [move](https://github.com/basho/yokozuna/commit/47d7448d3af4369bcc80f2d726324b74720ef7dd) (after discussion w/ @JeetKunDoug) to use riak_kv's 2.1 branch going forward on this maintenance yz branch.

Here's the 2.0 diff (since we discussed the next step of forwarding changes):

``` diff
diff --git a/rebar.config b/rebar.config
index 09aefa3..f4d98ec 100644
--- a/rebar.config
+++ b/rebar.config
@@ -13,9 +13,9 @@
   {kvc, ".*",
    {git, "git://github.com/etrepum/kvc.git", {tag, "v1.5.0"}}},
   {riak_kv, ".*",
-   {git, "git://github.com/basho/riak_kv.git", {branch, "2.0"}}},
-  {ibrowse, "4.0.1",
-   {git, "git://github.com/cmullaparthi/ibrowse.git", {tag, "v4.0.1"}}}
+   {git, "git://github.com/basho/riak_kv.git", {branch, "2.1"}}},
+  {ibrowse, "4.0.2",
+   {git, "git://github.com/cmullaparthi/ibrowse.git", {tag, "v4.0.2"}}}
  ]}.

 {pre_hooks, [{compile, "./tools/grab-solr.sh"}]}.
diff --git a/riak_test/yz_pb.erl b/riak_test/yz_pb.erl
index 2864e24..ea409c5 100644
--- a/riak_test/yz_pb.erl
+++ b/riak_test/yz_pb.erl
@@ -51,6 +51,8 @@ confirm() ->
     confirm_stored_fields(Cluster),
     confirm_search_non_existent_index(Cluster),
     confirm_search_with_spaced_key(Cluster),
+    confirm_create_index_within_timeout(Cluster),
+    confirm_create_index_not_within_timeout(Cluster),
     pass.

 select_random(List) ->
@@ -372,3 +374,61 @@ confirm_search_with_spaced_key(Cluster) ->
     Params = [{sort, <<"age_i asc">>}],
     store_and_search(Cluster, Bucket, Key,
                      Body, "application/json", <<"foo_i:5">>, Params).
+
+confirm_create_index_within_timeout(Cluster) ->
+    Index = <<"index_within_timeout">>,
+    Index1 = <<"index_within_infinity">>,
+    Bucket = {Index, <<"b1">>},
+    Node = select_random(Cluster),
+    [{Host, Port}] = host_entries(rt:connection_info([Node])),
+    {ok, Pid} = riakc_pb_socket:start_link(Host, (Port-1)),
+    lager:info("confirm_search_to_test_index_within_timeout ~p", [Bucket]),
+    NvalT = {n_val, 3},
+    Timeout = {timeout, 25000},
+    Timeout1 = {timeout, infinity},
+    ?assertEqual(ok,
+                 riakc_pb_socket:create_search_index(Pid, Index, [NvalT, Timeout])),
+    ?assertEqual(ok, element(1, riakc_pb_socket:get_search_index(Pid, Index, []))),
+
+    lager:info("confirm_search_to_test_index_within_infinity ~p", [Bucket]),
+    ?assertEqual(ok,
+                 riakc_pb_socket:create_search_index(Pid, Index1, [NvalT, Timeout1])),
+    ?assertEqual(ok,
+                 element(1, riakc_pb_socket:get_search_index(Pid, Index1, []))),
+
+    riakc_pb_socket:stop(Pid).
+
+confirm_create_index_not_within_timeout(Cluster) ->
+    Index = <<"index_not_within_timeout">>,
+    Bucket = {Index, <<"b1">>},
+    lager:info("confirm_search_to_test_index_not_within_timeout ~p", [Bucket]),
+    Node = select_random(Cluster),
+    [{Host, Port}] = host_entries(rt:connection_info([Node])),
+    {ok, Pid} = riakc_pb_socket:start_link(Host, (Port-1)),
+    riakc_pb_socket:set_options(Pid, [queue_if_disconnected]),
+
+    SchemaName = ?YZ_DEFAULT_SCHEMA_NAME,
+    %% Test invalid n_val
+    NValT = {n_val, bbbbbb},
+    %% Test invalid timeout value
+    Timeout = {timeout, asdasdasd},
+
+    NValT1 = {n_val, 3},
+    Timeout1 = {timeout, 10},
+
+    ?assertError(badarg, riakc_pb_socket:create_search_index(Pid, Index,
+                                                             SchemaName,
+                                                             [NValT1, Timeout])),
+    ?assertError(badarg, riakc_pb_socket:create_search_index(Pid, Index,
+                                                             SchemaName,
+                                                             [NValT, Timeout1])),
+
+    {error, <<"Index index_not_within_timeout not created on all the nodes within 10 ms timeout\n">>} =
+        riakc_pb_socket:create_search_index(
+          Pid, Index, SchemaName,
+          [NValT1, Timeout1]),
+
+    ok = yz_rt:wait_for_index(Cluster, Index),
+    ?assertEqual(ok,
+                 element(1, riakc_pb_socket:get_search_index(Pid, Index, []))),
+    riakc_pb_socket:stop(Pid).
diff --git a/src/yz_pb_admin.erl b/src/yz_pb_admin.erl
index 9da8998..282d4e6 100644
--- a/src/yz_pb_admin.erl
+++ b/src/yz_pb_admin.erl
@@ -109,9 +109,14 @@ process(#rpbyokozunaindexputreq{
             index = #rpbyokozunaindex{
                 name = IndexName,
                 schema = SchemaName,
-                n_val = Nval}}, State) ->
-    Timeout = app_helper:get_env(yokozuna, index_put_timeout_ms,
-                                 ?DEFAULT_IDX_CREATE_TIMEOUT),
+                n_val = Nval},
+            timeout = T0}, State) ->
+    Timeout =
+        case T0 of
+            undefined -> app_helper:get_env(yokozuna, index_put_timeout_ms,
+                                            ?DEFAULT_IDX_CREATE_TIMEOUT);
+            Set -> Set
+        end,

     case maybe_create_index(IndexName, SchemaName, Nval, Timeout) of
         ok ->
diff --git a/src/yz_wm_index.erl b/src/yz_wm_index.erl
index 2cf624f..e69e4c9 100644
--- a/src/yz_wm_index.erl
+++ b/src/yz_wm_index.erl
@@ -191,10 +191,7 @@ create_index(RD, S) ->
     BodyProps = S#ctx.props,
     Timeout =
         case S#ctx.timeout of
-            undefined -> app_helper:get_env(
-                          yokozuna,
-                          index_put_timeout_ms,
-                          ?DEFAULT_IDX_CREATE_TIMEOUT);
+            undefined -> ?DEFAULT_IDX_CREATE_TIMEOUT;
             Set -> Set
         end,
```

We'll need to pick-up

``` diff
diff --git a/src/yz_wm_index.erl b/src/yz_wm_index.erl
index 2cf624f..e69e4c9 100644
--- a/src/yz_wm_index.erl
+++ b/src/yz_wm_index.erl
@@ -191,10 +191,7 @@ create_index(RD, S) ->
     BodyProps = S#ctx.props,
     Timeout =
         case S#ctx.timeout of
-            undefined -> app_helper:get_env(
-                          yokozuna,
-                          index_put_timeout_ms,
-                          ?DEFAULT_IDX_CREATE_TIMEOUT);
+            undefined -> ?DEFAULT_IDX_CREATE_TIMEOUT;
             Set -> Set
         end,
```

in our no-ff, no-commit merge, forwarding changes from 2.0->2.1 (and then, 2.1->develop, afterward)

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@fadushin, moving my comment here :). It only fell out of line b/c we were focused on develop and tagging from there at one point.

No reconciliation was needed. Clean merge.

**Comment by fadushin** [comment]
Oops.  yeah, not sure how that happened.  My comment is at

https://github.com/basho/yokozuna/pull/521#issuecomment-117833221

Riak tests pass cleanly (Darwin and Linux) with these changes, with the proviso that previous be set to 2.0.5 (or lower, in the 2.0 series).  2.0.6 has changes that 3 of the upgrade tests below fail, but it's clean against 2.0.5.

Test Results:
yz_wm_extract_test-bitcask              : pass
yz_stat_test-bitcask                    : pass
yz_solr_start_timeout-bitcask           : pass
yz_siblings-bitcask                     : pass
yz_security-bitcask                     : pass
yz_schema_admin-bitcask                 : pass
yz_rs_migration_test-bitcask            : pass
yz_ring_resizing-bitcask                : pass
yz_pb-bitcask                           : pass
yz_monitor_solr-bitcask                 : pass
yz_mapreduce-bitcask                    : pass
yz_languages-bitcask                    : pass
yz_index_admin-bitcask                  : pass
yz_handoff_blocking-bitcask             : pass
yz_handoff-bitcask                      : pass
yz_fallback-bitcask                     : pass
yz_extractors-bitcask                   : pass
yz_errors-bitcask                       : pass
yz_ensemble-bitcask                     : pass
yz_dt_test-bitcask                      : pass
yz_default_bucket_type_upgrade-bitcask  : pass
yz_crdt-bitcask                         : pass

## yz_core_properties_create_unload-bitcask: pass

0 Tests Failed
23 Tests Passed
That's 100.0% for those keeping score

real    61m0.819s
user    14m11.888s
sys 8m18.815s

+1  47d7448

**Comment by JeetKunDoug** [comment]
:+1: 47d7448

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Pull request merged**
