### PR TITLE
When clearing a tree clear its stats too

### PR DESCRIPTION
**Pull request by rzezeski**
When a tree is cleared (erased from disk) the corresponding build
status should also be reset.  That is, the `riak-admin search
aae-status` command should display `--` for the last time the tree was
built since it is _not_ built.

### CODE REVIEW

**Comment by rzezeski** [comment]
## To Test

Build a cluster or single node with Yokozuna enabled.  Start the
cluster, wait a minute, then check `aae-status`.

```
# ./rel/riak/bin/riak-admin search aae-status
...
================================ Entropy Trees ================================
Index                                              Built (ago)
-------------------------------------------------------------------------------
0                                                  2.1 min
22835963083295358096932575511191922182123945984    2.1 min
45671926166590716193865151022383844364247891968    2.1 min
68507889249886074290797726533575766546371837952    2.1 min
91343852333181432387730302044767688728495783936    2.1 min
114179815416476790484662877555959610910619729920   2.1 min
137015778499772148581595453067151533092743675904   2.1 min
159851741583067506678528028578343455274867621888   2.1 min
182687704666362864775460604089535377456991567872   2.1 min
205523667749658222872393179600727299639115513856   2.1 min
228359630832953580969325755111919221821239459840   2.1 min
251195593916248939066258330623111144003363405824   2.1 min
...
```

Attach to one of the nodes and clear all trees.

```
# ./rel/riak/bin/riak attach-direct
> riak_core_util:rpc_every_member_ann(yz_entropy_mgr, clear_trees, [], infinity).
```

Check `aae-status` again.  The trees should be marked as `--` which
means that tree is not built.

```
# ./rel/riak/bin/riak-admin search aae-status
...
================================ Entropy Trees ================================
Index                                              Built (ago)
-------------------------------------------------------------------------------
0                                                  --
22835963083295358096932575511191922182123945984    --
45671926166590716193865151022383844364247891968    --
68507889249886074290797726533575766546371837952    --
91343852333181432387730302044767688728495783936    --
114179815416476790484662877555959610910619729920   --
137015778499772148581595453067151533092743675904   --
159851741583067506678528028578343455274867621888   --
182687704666362864775460604089535377456991567872   --
205523667749658222872393179600727299639115513856   --
228359630832953580969325755111919221821239459840   --
251195593916248939066258330623111144003363405824   --
...
```

**Comment by rzezeski** [comment]
This is needed for #20 as it makes explaining migration from legacy search much easier.

**Comment by coderoshi** [comment]
+1 24fab5d
- [x] review
- [x] manual test

**Comment by rzezeski** [comment]
@borshop merge

**Pull request merged**
