### PR TITLE
Don't wait for riak_kv service

### PR DESCRIPTION
**Pull request by rzezeski**
Forcing Yokozuna to wait for the riak_kv service causes all
applications which start after Yokozuna to wait.  This can come at the
detriment of those applications.  I've also been told this can crash
the Riak node if an application takes too long to start.

I'm confident I had good reasons for originally waiting for the
riak_kv service.  I believe it had to do with Yokozuna start-up
requiring KV reads around schemas and other such things.  This was
probably related an older implementation of the default index.  The
default index has since been entirely removed.

A race may still exist, but a KV read may fail for many reasons.
Yokozuna should face the harsh reality that a read may fail and deal
with it as best as possible.  Yokozuna shouldn't wait for the riak_kv
service, negatively affecting other applications, just to avoid a
particular race that can be dealt with in a more fundamental way.

### CODE REVIEW

**Comment by rzezeski** [comment]
This addresses #177.

**Comment by rzezeski** [comment]
All tests passed for me with exception of `yz_rs_migration` which is known failure ATM.

```
Test Results:
23:04:39.579 [info] Stopped Node... /spinning/yz-verify/rt/riak_yz/dev/dev5/bin/riak stop ~ wasn't running.
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration-bitcask      : fail
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_flag_transitions-bitcask  : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
```

**Comment by jrwest** [comment]
:). will double check it fixes my issue in the AM

**Comment by coderoshi** [comment]
Also works for me. That proves nothing, but honestly, I can't think of a reason for waiting either.

+1

**Comment by jrwest** [comment]
Bah sorry, I tested this but forgot to actually comment. wfm as well. +1. 

Jordan

**Pull request merged**
