### PR TITLE
Add coding statement to files using utf8 chars

### PR DESCRIPTION
**Pull request by coderoshi**
Noticed by @macintux, two of our test files didn't follow the http://www.erlang.org/doc/apps/stdlib/unicode_usage.html guideline for defining utf8 encoding.

### CODE REVIEW

**Comment by coderoshi** [comment]
overexuberant PRing.

**Comment by macintux** [comment]
For the record, credit goes to @shino for alerting me to the problem

**Comment by rzezeski** [comment]
My reading of that Erlang page makes me believe we should have this pragma. From what I can tell it is documented as required in order to use string literals containing character sets outside of latin-1. @macintux did you find otherwise using 16B02? The documentation also makes me believe that binary literals containing non latin-1 require a `/utf8` suffix. Did I misunderstand the documentation?

**Comment by macintux** [comment]
My experimentation led me to believe coding pragma and `/utf8` are both necessary for correct processing.

**Comment by coderoshi** [comment]
I closed this PR because the branch was broken, and intended to reopen. But I see it has been. It's ready for review now.

**Comment by hazen** [comment]
Failed at first, but once I updated my basho_bench and riak_test I get

```
Test Results:
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : pass
yz_ring_resizing-bitcask     : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
0 Tests Failed
18 Tests Passed
That's 100.0% for those keeping score
```

:+1:

**Pull request merged**
