### PR TITLE
force 404 check on ping/healthcheck for exists check

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
(cherry picked from commit 6a360fa78845c3ae652a3fc76e368c31661608d2)

This will probably be only used for patches until 2.0.6 is out, but here anyway for discussion, etc...

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@fadushin not sure if we want to merge this in, as the _original_ plan was building 2.0.6 (and updating 2.0 accordingly) from develop (which will need to include https://github.com/basho/yokozuna/pull/500 (still waiting on merge if we go that route). 

The newer plan, after we then update the 2.0 branch... going forward, we will make incremental changes of the 2.0/2.1/etc branches respectively and merging forward into develop (unless we're doing something breaking off develop). 

If we want to backport work from develop into 2.0, just make sure things get properly rebased on 2.0, so we don't lose the history. Honestly, I'm good to start that process now, but there's been a good # of commits to develop that are not on 2.0. Please also read the email I sent about patching this w/ any 2.1 code we've patched before :). Thanks.

**Comment by fadushin** [comment]
+1 0a34d49

**Comment by jonmeredith** [comment]
@borshop retry

**Comment by zeeshanlakhani** [comment]
Being that I saw this one getting a +1... I wanted to add the fix to the schema_admin test w/ the new ping and this is **only** related to the backport.

**Comment by zeeshanlakhani** [comment]
:+1: e3e62e149ca153c887fdc85993962254335d30ff

**Comment by jonmeredith** [comment]
@borshop retry

**Comment by jonmeredith** [comment]
@borshop merge

**Comment by fadushin** [comment]
Merging by hand with the blessing of the team, given Bors' inability to work with this PR.

**Pull request merged**
