### PR TITLE
Replace regexp with list replace

### PR DESCRIPTION
**Pull request by coderoshi**
Expanding on the prematurely merged #410

@andrewjstone @jonmeredith

### CODE REVIEW

**Comment by andrewjstone** [comment]
:+1: 9fdb645

You may want to rebase and squash these all into one commit. Up to you as yoko master.

**Comment by coderoshi** [comment]
@andrewjstone squashed, want to +1 this?

**Comment by andrewjstone** [comment]
:+1: c1de84b

**Comment by coderoshi** [comment]
@borshop merge

**Pull request merged**
