### PR TITLE
Correctly set Jetty temp directory

### LINKED ISSUE #387: Look at this issue in node_package
https://github.com/basho/node_package/issues/138

I don't feel we should have to create any directories as part of the packaging.  I thought jetty/solr was creating a relative dir.  Needs investigating...

### PR DESCRIPTION
**Pull request by rzezeski**
Fixes #387.

A custom `solr-jetty-context.xml` must be used so that the
`tempDirectory` is set properly.  `jetty.home` is a system property,
not a regular property.

### CODE REVIEW

**Comment by rzezeski** [comment]
You can test this by starting a Riak node without this change and notice that `solr-webapp` is under the root dir of riak (i.e. `dev/dev#` or `rel/riak`).  With this change `solr-webapp` will be under `{root}/lib/yokozuna/priv/solr/solr-webapp`.

**Comment by coderoshi** [comment]
Looks good. Just needs a rebase then +1

**Comment by rzezeski** [comment]
@coderoshi rebased

**Comment by coderoshi** [comment]
+1 fd37257

**Comment by rzezeski** [comment]
@reiddraper what does it mean when borshop fails to merge into its integration branch?  A merge conflict?

**Comment by rzezeski** [comment]
@borshop merge

**Pull request merged**
