### PR TITLE
Add thumbs config test

### PR DESCRIPTION
**Pull request by davidx**

### CODE REVIEW

**Comment by ooshlablu** [comment]
:+1:

**Comment by davidx** [comment]
I guess they need to be 2 non author reviews, so mine wont count. I'll use basho ops

**Comment by BashoOps** [comment]
+1

**Comment by JeetKunDoug** [comment]
+1

**Comment by ooshlablu** [comment]
:+1:

**Comment by davidx** [comment]
hi

**Comment by BashoOps** [comment]
+1

**Comment by BashoOps** [comment]
lets try that again ? +1

**Comment by ooshlablu** [comment]
and again: +1

**Pull request merged**
