### PR TITLE
Add support for ensemble tombstone value

### PR DESCRIPTION
**Pull request by coderoshi**
Ensemble uses a special `notfound` atom to represent a tombstone on a node. This checks for that value, and triggers a delete if it exists. The related test lives basho/riak_test#650.

### CODE REVIEW

**Comment by jonmeredith** [comment]
@coderoshi is this for review for the RC? Needs milestone set and a reviewer.

**Comment by andrewjstone** [comment]
- [x] code review
- [x] riak_test
- [x] dialyzer
- [x] xref

**Comment by andrewjstone** [comment]
Riak Test is currently failing. See https://github.com/basho/riak_test/pull/650/files#r14093184

**Comment by coderoshi** [comment]
@andrewjstone addressed in that PR

**Comment by andrewjstone** [comment]
:+1: caf025a

**Comment by coderoshi** [comment]
@borshop merge

**Pull request merged**
