### PR TITLE
Added special handling for upgrades from 2.0.8 [JIRA: RIAK-3384]

### PR DESCRIPTION
**Pull request by fadushin**
This PR fixes upgrades from 2.0.8, to allow seamless upgrades to new solrconfigs from all 2.0.x versions.  The change is needed because the default solrconfig.xml file changed slightly in 2.0. to adjust the commit time (to account for batching latency), and we failed to pick up that change in the upgrade logic.

### CODE REVIEW

**Comment by bsparrow435** [comment]
+1

**Comment by ian-mi** [comment]
+1

**Comment by fadushin** [comment]
thumbot merge

**Comment by bashopatricia** [comment]
create jira issue

**Pull request merged**
