### PR TITLE
Fix deletion for many-to-one indexing

### LINKED ISSUE #376: deletion broken for many-to-one indexing
Deletion is broken for many-to-one indexing.  Yokozuna deletes based
on Riak Key only.  If multiple types or buckets point to the same
index then it is possible for the same key to exist multiple times.
The current code would cause all instances of the key to be deleted.

Any deletes performed as queries (i.e. `{key,Key}` or
`{siblings,Key}`) must be updated to include the type and bucket name.

### PR DESCRIPTION
**Pull request by rzezeski**
Fixes #376.

It is possible to point multiple types and buckets to the same index.
The object key alone is not a unique identifier as the same key could
be repeated across types and buckets.

This patch fixes the deletion code to delete on the actual unique key
which is type + bucket + key.  Other changes made include:
- Expand the essential test to verify deletion and sibling cleanup
  work correctly when using the same key across multiple types and
  buckets.  Add unicode and special chars to additional verification.
- Update the AAE test to to pass the full key when making remote call
  to `yz_solr:delete`.
- Use the ?DEFAULT_TYPE macro in case the default type is changed
  before 2.0.0.
- Change `yz_rt:random_keys` to return binary keys.
- Handle legacy objects (pre 2.0.0) in `encode_delete`.
- Make sure to pass the lager transform when compiling the Yokozuna
  driver and make the `build_bb_driver` function more robust in
  general.

### CODE REVIEW

**Comment by rzezeski** [comment]
This also addresses my comment on #351.

https://github.com/basho/yokozuna/pull/351#issuecomment-43517810

**Comment by coderoshi** [comment]
Good call on using ?DEFAULT_TYPE. There are a couple other modules that still hard-code <<"default"">>, fwiw:
- src/riak_object_json.erl
- riak_test/yz_schema_admin.erl

**Comment by coderoshi** [comment]
- [x] Code Review
- [x] Compile/Unit Test
- [x] Dialyzer
- [x] Riak Test
- [x] Manual Test

```
Test Results:
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : pass
yz_ring_resizing-bitcask     : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
0 Tests Failed
18 Tests Passed
That's 100.0% for those keeping score
```

**Comment by coderoshi** [comment]
+1 35dd283

**Comment by rzezeski** [comment]
@borshop merge

Yes, those other places should be updated too.  I'll change them in my next PR to avoid holding up this merge.

**Pull request merged**
