### PR TITLE
Add console module with AAE status

### PR DESCRIPTION
**Pull request by rzezeski**
Add a module for use with the riak console commands (riak/riak-admin).
Add the aae-status command for reporting AAE status such as trees built,
exchanges done, and keys repaired.

### CODE REVIEW

**Comment by rzezeski** [comment]
This addresses part of #20 as well as #292.

**Comment by rzezeski** [comment]
Buildbot fails because this requires basho/riak_kv#879..

**Comment by rzezeski** [comment]
Reminder that I need to create a docs PR for the new search subcommand.

**Comment by rzezeski** [comment]
Reminder that the man pages need to be updated.

**Comment by jaredmorrow** [comment]
+1, works with riak_kv and riak PR's.

**Pull request merged**
