### PR TITLE
force 404 check on ping/healthcheck for exists check

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
Related to customer issue... extra check if solr drops a request for exists. 
- Also... better logging around index deltas.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
^^ @fadushin @joecaswell @kesslerm @bsparrow435

**Comment by kesslerm** [comment]
Looks good to me.

**Comment by bsparrow435** [comment]
:+1: 6a360fa78845c3ae652a3fc76e368c31661608d2

**Comment by fadushin** [comment]
I really think this patch should be done off the 2.0 branch, tested, merged, and then forward merged to 2.1 and then to develop.  (or whatever the semantic versioning counterparts are for yokozuna)

**Comment by zeeshanlakhani** [comment]
@fadushin... yeah... i thought we were going to move to that approach after cutting 2.0.6/2.1.2, which will come off dev. But, you're right about opening this against 2.0 too. I'll open up a second PR.

**Comment by fadushin** [comment]
@borshop merge

**Pull request merged**
