### PR TITLE
fix issue with sync index EXIT b/c of atom already being in global regis...

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
...tery

### CODE REVIEW

**Comment by bearcage** [comment]
Tests pass locally with https://github.com/basho/riak-erlang-client/pull/208 applied; going to spend a little more time sorting out the builder failure there.

**Comment by zeeshanlakhani** [comment]
@aberghage cool... will wait to see how it goes w/ the builder (for https://github.com/basho/riak-erlang-client/pull/208). Let me know. Would like to officially have this ready for 2.1 or w/e.

**Comment by bearcage** [comment]
+1 365656a

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Pull request merged**
