### PR TITLE
Fix typo in log entry

### PR DESCRIPTION
**Pull request by roooms**

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
:+1:  a03c7ae

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
The fix is on the yokozuna 2.0 and 2.1 branches. 

**_[posted via JIRA by Mark Allen]**_

**Comment by Basho-JIRA** [comment]
Verified that this fix exists on 2.0 and 2.1 branches. 

**_[posted via JIRA by Mark Allen]**_

**Pull request merged**
