### PR TITLE
Upgrade to Solr 4.7.0

### PR DESCRIPTION
**Pull request by rzezeski**
Upgrade to Solr 4.7.0 with custom Yokozuna patches.
- Create custom 4.7.0 package that includes Yokozuna patches and
  upload to Basho's S3.
- Pull the new package.
- Remove stopword and other configuration files from source tree. Copy
  from package to stay in sync.
- Add Kurdish language support.
- Update to the latest Lucene 4.7 codecs.

See the commit messages for more info.

Note: The aae_test and yz_rs_migration_test will fail against this
PR. The migration test has been failing and the AAE test is related to
the segfault issue in eleveldb (basho/eleveldb#104).

### CODE REVIEW

**Comment by rzezeski** [comment]
This addresses #332.

**Comment by rzezeski** [comment]
Correction, it looks like basho/eleveldb#104 has been merged and I'm seeing all tests pass now. So as long as you run the latest everything should pass.

**Comment by coderoshi** [comment]
- [x] compile/unit
- [x] dialyzer
- [x] riak tests
- [x] code review
- [x] manual testing

I nuked everything from orbit, and AAE still fails for me. I'm not certain this failure is related, so I'm willing to +1 this.

```
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : fail
yz_ring_resizing-bitcask     : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : fail
---------------------------------------------
2 Tests Failed
16 Tests Passed
That's 88.88888888888889% for those keeping score
```

```
================ aae_test failure stack trace =====================
{{assertEqual_failed,[{module,aae_test},
                      {line,273},
                      {expression,"RepairCount"},
                      {expected,47},
                      {value,45}]},
 [{aae_test,'-verify_repair_count/2-fun-0-',2,
            [{file,"riak_test/aae_test.erl"},{line,273}]},
  {aae_test,verify_repair_count,2,
            [{file,"riak_test/aae_test.erl"},{line,273}]},
  {aae_test,confirm,0,[{file,"riak_test/aae_test.erl"},{line,69}]}]}
===================================================================
```

**Comment by rzezeski** [comment]
It passed for me two times in a row. I nuked everything but the deps
for riak.

```
cd yokozuna && rm -rf deps && make clean
cd yz-verify && rm -rf riak_yz/dev rt
```

Then I ran `aae_test` 10 times; it passed each time.

```
# grep ': pass$' verify-470-aae-*.txt
verify-470-aae-1.txt:aae_test-bitcask: pass
verify-470-aae-10.txt:aae_test-bitcask: pass
verify-470-aae-2.txt:aae_test-bitcask: pass
verify-470-aae-3.txt:aae_test-bitcask: pass
verify-470-aae-4.txt:aae_test-bitcask: pass
verify-470-aae-5.txt:aae_test-bitcask: pass
verify-470-aae-6.txt:aae_test-bitcask: pass
verify-470-aae-7.txt:aae_test-bitcask: pass
verify-470-aae-8.txt:aae_test-bitcask: pass
verify-470-aae-9.txt:aae_test-bitcask: pass
```

Then I blew away Riak completely in case the deps had changed again
and reintroduced a bug. I did three more runs all of which passed.

```
cd yz-verify && rm -rf riak_yz rt
```

```
# grep ': pass$' verify-470-aae-1{1,2,3}.txt
verify-470-aae-11.txt:aae_test-bitcask: pass
verify-470-aae-12.txt:aae_test-bitcask: pass
verify-470-aae-13.txt:aae_test-bitcask: pass
```

Perhaps there is a race in the test. I'll try running on my laptop but
I have a horrible internet connection right now.

**Comment by rzezeski** [comment]
Still having trouble running on my MBP because of horrible DSL
internet connection. I tried 3 passes with leveldb and memory on my
server and all passed. I thought maybe different backends could
introduce a race.

```
# grep ': pass$' verify-470-aae-1{4,5,6}.txt
verify-470-aae-14.txt:aae_test-eleveldb: pass
verify-470-aae-15.txt:aae_test-eleveldb: pass
verify-470-aae-16.txt:aae_test-eleveldb: pass

# grep ': pass$' verify-470-aae-1{7,8,9}.txt
verify-470-aae-17.txt:aae_test-memory: pass
verify-470-aae-18.txt:aae_test-memory: pass
verify-470-aae-19.txt:aae_test-memory: pass
```

**Comment by rzezeski** [comment]
I stood up a m1.large instance on EC2 running Ubuntu and the test
passed 6 times thus far. Either this test has a race or it's your
environment. In any case I can't reproduce.

```
$ grep ': pass$' verify-470-aae-*.txt
verify-470-aae-linux-1.txt:aae_test-bitcask: pass
verify-470-aae-linux-2.txt:aae_test-bitcask: pass
verify-470-aae-linux-3.txt:aae_test-bitcask: pass
verify-470-aae-linux-4.txt:aae_test-bitcask: pass
verify-470-aae-linux-5.txt:aae_test-bitcask: pass
verify-470-aae-linux-6.txt:aae_test-bitcask: pass
```

**Comment by rzezeski** [comment]
Of course, the second I post that I realized the linux runs were on develop. I'll have to re-run tomorrow.

**Comment by rzezeski** [comment]
I reran 6 times today on my Ubuntu box with the right branch this
time. I deleted my rt and riak_yz/dev dir before running.

```
$ git status
# On branch rz/upgrade-solr-4.7
```

```
$ grep ': pass$' verify-470-aae-linux-*
verify-470-aae-linux-1.txt:aae_test-bitcask: pass
verify-470-aae-linux-2.txt:aae_test-bitcask: pass
verify-470-aae-linux-3.txt:aae_test-bitcask: pass
verify-470-aae-linux-4.txt:aae_test-bitcask: pass
verify-470-aae-linux-5.txt:aae_test-bitcask: pass
verify-470-aae-linux-6.txt:aae_test-bitcask: pass
```

**Comment by coderoshi** [comment]
I ran this on my other MBP, and AAE passed. I'm at a loss, but whatever it is I doubt it's related to this PR

**Pull request merged**
