### PR TITLE
Speedup verify

### PR DESCRIPTION
**Pull request by rzezeski**
Just 2 small tweaks to speed up verify a little.

### CODE REVIEW

**Comment by hazen** [comment]
Ran verify.sh on this and got two failures:

```
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : fail
yz_rs_migration_test-bitcask : fail
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
2 Tests Failed
15 Tests Passed
That's 88.23529411764706% for those keeping score
```

I know you mentioned that migration is broken, but was not sure about the schema admin problem

**Comment by rzezeski** [comment]
Other way around, schema admin is broken. What is the failure for migration test? What is your `rt_max_wait_time` in `.riak_test.config`?

**Comment by hazen** [comment]
`{rt_max_wait_time, 600000},`

I have an idea about my 1.4.2 setup. Let me retest.

**Comment by hazen** [comment]
That was not the problem.  Here's the error on the migration test (which looks familiar):

```
================ yz_rs_migration_test failure stack trace =====================
{{assertEqual_failed,[{module,rtdev},
                      {line,232},
                      {expression,"file : write_file ( ConfigFile , NewConfigOut )"},
                      {expected,ok},
                      {value,{error,enoent}}]},
 [{rtdev,'-update_app_config_file/2-fun-3-',3,
         [{file,"src/rtdev.erl"},{line,232}]},
  {rtdev,update_app_config_file,2,[{file,"src/rtdev.erl"},{line,232}]},
  {rt,'-pmap/2-fun-0-',4,[{file,"src/rt.erl"},{line,1193}]}]}
===============================================================================
```

**Comment by hazen** [comment]
OK, after some initial operator malfunction, we are looking good:

```
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : fail
yz_rs_migration_test-bitcask : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
1 Tests Failed
16 Tests Passed
That's 94.11764705882352% for those keeping score
```

:+1:

**Comment by rzezeski** [comment]
Thanks for the review.

**Pull request merged**
