### PR TITLE
Confbal schema changes for Yokozuna

### PR DESCRIPTION
**Pull request by joedevivo**
- Made a 'search.solr.*' namespace
- Edited documentation
- changed search's datatype to flag
- added directory datatorp where appropriate.

### CODE REVIEW

**Comment by rzezeski** [comment]
Why the change to `search.solr`?

**Comment by joedevivo** [comment]
We thought it would be a logical grouping of settings. They're all related to how Solr works, and passing options to Solr. It just seemed to make semantic sense.

**Comment by rzezeski** [comment]
Looks good, +1.

**Comment by joedevivo** [comment]
@rzezeski we needed ProdMgmt +1 and CSE +1 before merging. Let me see if I can't get them retroactively :)

**Comment by rzezeski** [comment]
LOL, I assumed you already got that. Gonna leave them in. If someone has a problem just make a new PR.

**Comment by joedevivo** [comment]
haha. We were using PRs as the system of record. No worries.

**Comment by joedevivo** [comment]
@gburd @jmshoffs0812 a posthumous +1 would be great here :)

**Comment by angrycub** [comment]
+1 after reviewing all files.

**Pull request merged**
