### PR TITLE
Fix various issues re deleting documents

### PR DESCRIPTION
**Pull request by rzezeski**
This is a fix for #370. 

Jimmy Mullen, with the help of a user, discovered issues deleting keys
which contain curly braces.  A patch was made recently to wrap the key
in double quotes (Lucene phrase query) but it turns out there were
other issues with the code.
- Don't url encode the key.  The keys are not stored url encoded and
  the query is being sent as a body of JSON, not
  `application/x-www-form-urlencoded`.
- Don't perform a `binary_to_list`.  This breaks keys with non-latin
  characters.
- Don't build up a list when a binary can be used.  This should be
  more efficient than `++`.
- Use the term query parser for future safety.  Just quoting works now
  but future changes like the complex phrase query syntax could cause
  issues.  The use of the term query parser protects the characters
  from parsing (with 2 exceptions noted next).
- Escape any double quote or backslash characters.  The double quote
  must be escaped because double quotes are used to wrap the query.
  Backslash is escaped to prevent Solr from treating it as an escape
  sequence.

Other changes made:
- Modified the sibling test to use a key with various special
  characters and added a case for regular deletion.
- Removed dead code from `yz_solr`.
- Moved `delete_op` type to `yz_solr` and added docs for the various
  types.
- Use cons instead of `++` when building list of fields.

### CODE REVIEW

**Comment by rzezeski** [comment]
Benchmark results show a potential small dip (1%) in throughput and
raise in median latency.  Building binaries should be more efficient
than list concatenation but that gain is overshadowed by the use of
the two `binary:replace` calls.

|  | Throughput (Ops/s) | Median | 99th (ms) |
| --- | --- | --- | --- |
| current | 1496 | 12.84 ms | 112.48 ms |
| patch | 1482 | 13.21 ms | 110.53 ms |

**Comment by coderoshi** [comment]
- [x] code review
- [x] compile/unit
- [x] dialyzer
- [x] riak tests
- [x] manual testing

```
Test Results:
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : fail
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : pass
yz_ring_resizing-bitcask     : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
```

Security failure due to expired cert, unrelated to these changes.

**Comment by coderoshi** [comment]
+1 946e618

**Comment by rzezeski** [comment]
Same thing as other issue. Bors wants +1 on last commit.

**Comment by rzezeski** [comment]
@borshop merge

**Pull request merged**
