### PR TITLE
Fresh solr 2.9.1

### PR DESCRIPTION
**Pull request by asyncmind0**
Pull request with yokozuna updated to solr7

### CODE REVIEW

**Comment by martinsumner** [comment]
Plans for this at the moment.  I want to do run the riak_test tests this weekend, I suspect many won't pass (as already highlighted) - but if we can justify why, that's OK, and we can see what sort of test coverage we're left with.

I have an urgent need to cut riak 2.9.2 - so if there's anything I'm not sure about I'll hold off merging in until that release is completed.  I intend to put out a release candidate with this in soon after - but I may try and juggle two streams for now.

ASAP, I want to get this, and the backlog of 2.9 changes, into the 3.0 release.

**Comment by martinsumner** [comment]
Running riak_test, the majority of yokozuna tests pass:

```
yz_aae_test-bitcask: pass
yz_core_properties_create_unload-bitcask: pass
yz_crdt-bitcask: pass
yz_dt_test-bitcask: pass
yz_ensemble-bitcask: pass
yz_errors-bitcask: pass
yz_faceted_search-bitcask: pass
yz_fallback-bitcask: pass
yz_handoff-bitcask: pass
yz_handoff_blocking-bitcask: pass
yz_languages-bitcask: pass
yz_mapreduce-bitcask: pass
yz_monitor_solr-bitcask: pass
yz_pb-bitcask: pass
yz_ring_resizing-bitcask: pass
yz_security-bitcask: pass
yz_siblings-bitcask: pass
yz_solrq_test-bitcask: pass
yz_stat_test-bitcask: pass
yz_wm_extract_test-bitcask: pass
```

Some test fail, but are tests of upgrades which we therefore wouldn't expect to pass:

```
yz_default_bucket_type_upgrade-bitcask: fail -  upgrade test
yz_extractors-bitcask: fail - upgrade test
yz_fuse_upgrade-bitcask: fail - upgrade test
yz_solr_upgrade_downgrade-bitcask: fail - upgrade test
```

There are some other test failures though.  These might be explained by simple changes (e.g. to the solr rest API), so potentially could be easily solvable:

```
yz_entropy_data-bitcask: fail - url Issue?
yz_index_admin-bitcask: fail - url issue?
yz_schema_admin-bitcask: fail - cannot ping node after schema correction
yz_schema_change_reset-bitcask: fail - may also be ping related after schema change
yz_search_http-bitcask: fail - 500 error (not 415) on non-applicable content-type
yz_solr_start_timeout-bitcask: fail - looks for "alloted time" when actual phrase is "allowed time"
yz_startup_shutdown-bitcask: fail - query processes fail could be url issue?
```

**Comment by martinsumner** [comment]
A bigger set of problems after merging into 3.0:

```
yokozuna_essential-bitcask: fail
yz_aae_test-bitcask: pass
yz_core_properties_create_unload-bitcask: pass
yz_crdt-bitcask: fail
yz_dt_test-bitcask: pass
yz_ensemble-bitcask: pass
yz_errors-bitcask: pass
yz_entropy_data-bitcask: fail
yz_faceted_search-bitcask: pass
yz_fallback-bitcask: pass
yz_handoff-bitcask: pass
yz_handoff_blocking-bitcask: pass
yz_index_admin-bitcask: fail
yz_languages-bitcask: pass
yz_mapreduce-bitcask: fail
yz_monitor_solr-bitcask: pass
yz_pb-bitcask: fail
yz_ring_resizing-bitcask: pass
yz_schema_admin-bitcask: fail
yz_schema_change_reset-bitcask: fail
yz_search_http-bitcask: fail
yz_security-bitcask: pass
yz_siblings-bitcask: fail
yz_solr_start_timeout-bitcask: fail
yz_solrq_test-bitcask: pass
yz_startup_shutdown-bitcask: fail
yz_stat_test-bitcask: pass
yz_wm_extract_test-bitcask: pass
```

**Comment by martinsumner** [comment]
The failure of `yokozuna_essential` and `yz_pb` both appear to be related to different handling of unicode within OTP20+.  Both tests pass multiple sub-tests until hitting one with unicode data/keys.

**Comment by martinsumner** [comment]
The failure of `yz_mapreduce` is related to the deprecation of JS-map/reduce.  The test needs to be changed to use inbuilt erlang map/reduce functions.

**Comment by martinsumner** [comment]
The failure of `yz_crdt` appears to be an in issue with an intercept function

**Comment by asyncmind0** [comment]
deprecated by https://github.com/basho/yokozuna/pull/766

**Pull request closed without merging**
