### PR TITLE
REL-69: Move YZ tests from riak_test to yokozuna 2.0

### PR DESCRIPTION
**Pull request by hazen**

### CODE REVIEW

**Comment by fadushin** [comment]
I think we also want to move src/yokozuna_rt to yokozuna, but this is a little more subtle, as it probably requires merging yokozuna_rt from riak_test and the yz_rt utility module in yokozuna.

**Comment by hazen** [comment]
As mentioned in Slack, I'll try this again with that merge you suggested

**Comment by javajolt** [comment]
Initial test results:
```
Test Results:
yz_pb-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                           : fail
yz_monitor_solr-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                 : pass
yz_mapreduce-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                    : pass
yz_languages-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                    : pass
yz_index_admin-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                  : fail
yz_handoff_blocking-riak_kv_bitcask_backend,riak_kv_eleveldb_backend             : fail
yz_handoff-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : fail
yz_fuse_upgrade-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                 : fail
yz_fallback-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                     : fail
yz_faceted_search-riak_kv_bitcask_backend,riak_kv_eleveldb_backend               : pass
yz_extractors-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                   : fail
yz_errors-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                       : pass
yz_entropy_data-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                 : fail
yz_ensemble-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                     : pass
yz_dt_test-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : pass
yz_default_bucket_type_upgrade-riak_kv_bitcask_backend,riak_kv_eleveldb_backend  : pass
yz_crdt-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                         : pass
yz_core_properties_create_unload-riak_kv_bitcask_backend,riak_kv_eleveldb_backend: pass
yz_aae_test-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                     : pass
yokozuna_essential-riak_kv_bitcask_backend,riak_kv_eleveldb_backend              : pass
yz_wm_extract_test-riak_kv_bitcask_backend,riak_kv_eleveldb_backend              : pass
yz_stat_test-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                    : fail
yz_startup_shutdown-riak_kv_bitcask_backend,riak_kv_eleveldb_backend             : fail
yz_solrq_test-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                   : pass
yz_solr_start_timeout-riak_kv_bitcask_backend,riak_kv_eleveldb_backend           : pass
yz_siblings-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                     : pass
yz_security-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                     : pass
yz_search_http-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                  : fail
yz_schema_change_reset-riak_kv_bitcask_backend,riak_kv_eleveldb_backend          : pass
yz_schema_admin-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                 : pass
yz_rs_migration_test-riak_kv_bitcask_backend,riak_kv_eleveldb_backend            : fail
yz_ring_resizing-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                : pass
---------------------------------------------
12 Tests Failed
20 Tests Passed
That's 62.5% for those keeping score
```

Fixing the failures...

**Comment by fadushin** [comment]
C.f., https://github.com/basho/riak_test/pull/1272

+1

**Pull request merged**
