### PR TITLE
Delete dialyzer.ignore-warnings [JIRA: RIAK-3244]

### PR DESCRIPTION
**Pull request by nickelization**
Running Dialyzer on my local machine passes with no warnings, even with this entire file having been deleted. I suspect these are all obsolete.

### CODE REVIEW

**Comment by nickelization** [comment]
create jira issue

**Comment by fadushin** [comment]
+1

**Comment by fadushin** [comment]
Probably worth pointing out that there is no change in behavior with the code change, so by some standards no additional testing is required.

**Comment by bsparrow435** [comment]
+1

**Comment by JeetKunDoug** [comment]
@thumbot merge

**Pull request merged**
