### PR TITLE
* config and build script updates for pulling in solr 4.10.4 (solr bi…

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
…nary already pushed to uploads.basho). 

Handles **RIAK-1795**.
- minor updates to prevent benign but useless warnings in solr logs
- patch update for move to 4.10.4
- move to jdk 7 for building solr 4.10.4, as it's the min version required

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
# Benchies **(Local Runs -> OSX, 10.10, 2.7 GHz Intel, 16GB memory)**
- The multi-index PUT numbers will be ridiculously high for latency (and super-low for median throughput) for example b/c that's !50 Solr cores! (_search_indexes_) on just my machine and not a 'real' cluster, 50 cores on a Mac like mine is cra cra (just using Solr w/o Riak). This is just for comparison of the versions.

### Riak - Before - Change

**Query:** 
summary

**Multi-Index Put**:
summary

```
Mean ops/s for riak-current/before-load-fruit: 587.226813
Mean ops/s for riak-current/before-query-lima: 821.286146
Mean ops/s for riak-current/load-index: 0.233328
Mean ops/s for riak-current/multi-index: 0.230233
```

```
The mean 95th latency for riak-current/before-load-fruit/load-fruit-pb_latencies.csv: 104.417933
The mean 95th latency for riak-current/before-query-lima/random-fruit-search-pb-id-3-100000_latencies.csv: 64.791259
The mean 95th latency for riak-current/before-query-lima/search-pb-korlan-id-1_latencies.csv: 63.907889
The mean 95th latency for riak-current/load-index/load-indexes_latencies.csv: 7808.917611
The mean 95th latency for riak-current/multi-index/load-fruit-pb-per-index_latencies.csv: 37331.094674
```

```
The mean 99th latency for riak-current/before-load-fruit/load-fruit-pb_latencies.csv: 143.919533
The mean 99th latency for riak-current/before-query-lima/random-fruit-search-pb-id-3-100000_latencies.csv: 84.599852
The mean 99th latency for riak-current/before-query-lima/search-pb-korlan-id-1_latencies.csv: 83.759704
The mean 99th latency for riak-current/load-index/load-indexes_latencies.csv: 7861.378500
The mean 99th latency for riak-current/multi-index/load-fruit-pb-per-index_latencies.csv: 37331.094674
```

```
The mean median latency for riak-current/before-load-fruit/load-fruit-pb_latencies.csv: 52.799600
The mean median latency for riak-current/before-query-lima/random-fruit-search-pb-id-3-100000_latencies.csv: 38.249704
The mean median latency for riak-current/before-query-lima/search-pb-korlan-id-1_latencies.csv: 37.398926
The mean median latency for riak-current/load-index/load-indexes_latencies.csv: 7248.617833
The mean median latency for riak-current/multi-index/load-fruit-pb-per-index_latencies.csv: 35916.997070
```

### Riak - After - Change

**Query:** 
summary

**Multi-Index Put**:
summary

```
Mean ops/s for riak-change/before-load-fruit: 606.238712
Mean ops/s for riak-change/before-query-lima: 926.213036
Mean ops/s for riak-change/load-index: 0.241179
Mean ops/s for riak-change/multi-index: 0.316128
```

```
The mean 95th latency for riak-change/before-load-fruit/load-fruit-pb_latencies.csv: 104.664333
The mean 95th latency for riak-change/before-query-lima/random-fruit-search-pb-id-3-100000_latencies.csv: 55.434444
The mean 95th latency for riak-change/before-query-lima/search-pb-korlan-id-1_latencies.csv: 54.826259
The mean 95th latency for riak-change/load-index/load-indexes_latencies.csv: 5122.625059
The mean 95th latency for riak-change/multi-index/load-fruit-pb-per-index_latencies.csv: 31551.322387
```

```
The mean 99th latency for riak-change/before-load-fruit/load-fruit-pb_latencies.csv: 148.921867
The mean 99th latency for riak-change/before-query-lima/random-fruit-search-pb-id-3-100000_latencies.csv: 71.257185
The mean 99th latency for riak-change/before-query-lima/search-pb-korlan-id-1_latencies.csv: 70.307296
The mean 99th latency for riak-change/load-index/load-indexes_latencies.csv: 5174.356706
The mean 99th latency for riak-change/multi-index/load-fruit-pb-per-index_latencies.csv: 31551.322387
```

```
The mean median latency for riak-change/before-load-fruit/load-fruit-pb_latencies.csv: 48.761933
The mean median latency for riak-change/before-query-lima/random-fruit-search-pb-id-3-100000_latencies.csv: 33.618148
The mean median latency for riak-change/before-query-lima/search-pb-korlan-id-1_latencies.csv: 32.901704
The mean median latency for riak-change/load-index/load-indexes_latencies.csv: 4633.865412
The mean median latency for riak-change/multi-index/load-fruit-pb-per-index_latencies.csv: 29538.440548
```

**Comment by zeeshanlakhani** [comment]
Once develop is up-to-date, this should be rebased and reopened against it... probably re-benchmarked too. This was a microbenchmark, but we should test it against ec2.

**Comment by zeeshanlakhani** [comment]
For upgrading indexes, the key files to look at -- per-index directory -- are **priv/conf/_rest_managed.json** (new), **priv/conf/solrconfig.xml** (which they may have modified, but this one is key b/c the updated _Lucene version_), **priv/default_schema.xml** (if they are using the default schema). ^^ @JeetKunDoug @fadushin @jvoegele 

After talking to @JeetKunDoug, make work best as a riak-admin search call that runs the script.

**Comment by bsparrow435** [comment]
@fadushin anything left to do here?

**Comment by JeetKunDoug** [comment]
This PR is subsumed by the work already done in the 2.2 release - closing.

**Pull request closed without merging**
