### PR TITLE
Correspondence to Apache Lucene 4.5.x, and detailed change of java_scr 

### PR DESCRIPTION
**Pull request by masahitojp**
- It corresponds to Lucene-5114 [remove boolean useCache param from TermsEnum.seekCeil/Exact].
  https://issues.apache.org/jira/browse/LUCENE-5114
  
  TermsEnum.SeekStatus seekCeil(BytesRef text, boolean useCache) is removed@Lucene 4.5.x
- "final" is added to the variable which is not changed.
- The processing which judges whether it is effective in logger is added.

### CODE REVIEW

**Comment by rzezeski** [comment]
Thanks for the updates. Especially the preemptive fix to the seek call. That will save me some time when I upgrade to latest. I still have to run the integration tests but first I would like the commit message updated. The first line should be a concise summary, followed by a blank line, then followed by your list of changes. This plays better with standard git tools. You can just ammend the commit and force push.

**Comment by masahitojp** [comment]
Thank you for the point to a commit comment. 
It corresponded.

**Comment by rzezeski** [comment]
Great. I marked this for next release.

**Comment by rzezeski** [comment]
This PR is superseded by #243 which includes your original commit. I had to make a new branch because of conflicting changes. I'm closing this PR.

**Pull request closed without merging**
