### PR TITLE
Verify _yz fields are not multivalued

### LINKED ISSUE #211: Better schema validation
basho/riak-java-client#316

Based on the issue here see if schema verification can be improved.  Write a few more riak test scenarios and improve the checking around `_yz_id`.

### PR DESCRIPTION
**Pull request by rzezeski**
Fixes #211.

The _yz fields should never be multivalued.  Prevent users from
storing schemas that declare them as such.

### CODE REVIEW

**Comment by coderoshi** [comment]
- [x] compile/units
- [x] riak test
- [x] erlang schema test (basho/riak-erlang-client#170)
- [x] ruby schema test (basho/riak-ruby-client#163)
- [x] python schema test (basho/riak-python-client#333)
- [x] java schema test (basho/riak-java-client#430)
- [x] document new schema requirements (basho/basho_docs#1116)

Changes in this PR are fine, but also need to verify that any client tests work alongside this new requirement.

```
Test Results:
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : pass
yz_ring_resizing-bitcask     : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
0 Tests Failed
18 Tests Passed
That's 100.0% for those keeping score
```

**Comment by rzezeski** [comment]
@coderoshi I updated the docs: basho/basho_docs#1116

**Comment by coderoshi** [comment]
+1 33400ec

**Comment by rzezeski** [comment]
@borshop merge

**Pull request merged**
