### PR TITLE
Add JSON Object Value Generator

### PR DESCRIPTION
**Pull request by rzezeski**
Add `json_obj_valgen` to the Yokozuna BB driver. I used this to test
indexing "large" JSON objects while investigating #358.  The config
line to use this value generator looks like so:

```
{value_generator, {function, yz_driver, json_obj_valgen,
[<NumFields>]}}.
```

This will generate a static JSON object (i.e. generated once at start
up) which contains `<NumFields>` integer fields.  All workers will
index the identical object.  Here is an example config from one of my
testing runs:

```
{mode, max}.
{concurrent, 32}.
{driver, yz_driver}.
{code_paths, ["/root/work/yz-bb/misc/bench"]}.
{secure, false}.
{bucket, {<<"data">>, <<"largeobj">>}}.
{index, <<"largeobj">>}.
{pb_conns, [{"10.0.1.201", 8087}]}.
{http_conns, []}.
{duration, infinity}.
{key_generator, {to_binstr, "~B", {partitioned_sequential_int, 0,
1000}}}.
{value_generator, {function, yz_driver, json_obj_valgen, [4000]}}.
{operations, [{load_pb, 1}]}.
```

This uses 32 workers to write the same JSON object containing 4000
integer fields over the key space 0 to 999.

NOTE: I purposely hard coded the timeout to 90s for the purposes of my
testing.  Yes, ideally this would be configurable but this patch is
about minimal amount of work to achieve the task at hand.  Please keep
this in mind while reviewing.  This is a tool, not production code.

### CODE REVIEW

**Comment by lordnull** [comment]
Seems to work, after running with similar config (changed to default bucket and loopback IP), I'm able to see very large objects in my riaks. Only remaining concern is dialyzer failure.

**Comment by rzezeski** [comment]
> Only remaining concern is dialyzer failure.

Yea this needs to be rebased.  I'll get to that tomorrow.  Thanks for reviewing this.

**Comment by rzezeski** [comment]
@lordnull Rebased and buildbot shows a good build.

**Comment by lordnull** [comment]
:+1:

**Comment by rzezeski** [comment]
@lordnull you need to +1 the commit for bors to pick it up.

**Comment by lordnull** [comment]
:+1:  f44cee2

**Comment by rzezeski** [comment]
@borshop merge

**Pull request merged**
