### PR TITLE
Upgrade Solr to Version 4.6.1

### PR DESCRIPTION
**Pull request by hazen**
Upgraded YZ to build using solr-4.6.1.  Also added @rzezeski's benchmarking documentation with a couple of updates to run a 5-node **devrel** cluster, create an index and work around the `riak_pb` build issues.

At the moment `solr-4.6.1-yz.tgz` has been uploaded to http://s3.amazonaws.com/files.basho.com/solr with a SHA1 of

```
e60ff7926b9cd7c82bf94d89529c9dc60219e753  solr-4.6.1-yz.tgz
```

Fruit load performance yielded the following results:

| Load | Throughput (Ops/s) | Median (ms) | 99th (ms) |
| --- | --- | --- | --- |
| Current | 1128.22 | 22.35 | 114.77 |
| Solr 4.6.1 | 1113.68 (-1.30%) | 22.71 (+1.02%) | 116.52 (+1.02%) |

| Query | Throughput (Ops/s) | Median (ms) | 99th (ms) |
| --- | --- | --- | --- |
| Current | 1696.92 | 18.35 | 38.53 |
| Solr 4.6.1 | 1688.69 (-0.49%) | 18.43 (+0.44%) | 38.89 (+0.94%) |

This addresses #288

### CODE REVIEW

**Comment by rzezeski** [comment]
Go ahead and upload the custom Solr tar to `files.basho.com/solr/` along with a SHA1 of that tar in case we want to verify SHA in the future. Then change the `grab-solr.sh` to pull from new location.

**Comment by rzezeski** [comment]
- [x] review code
- [x] make & eunit
- [x] dialyzer
- [x] riak tests
- [ ] <del>verify perf</del>

**Comment by rzezeski** [comment]
Okay, some of the tests failed but that's because of the n-val changes. The Erlang client changes in basho/riak-erlang-client#154 need to be merged as well as the server side changes in #295. It appears the riak tests were never run to make sure both client & server changes work together. The `yz_pb` (and perhaps other tests) need to be modified to account for `n_val` being in the record. This also means I can't run the perf tests.

Other than that this PR looks good to me. Let's merge it in and deal with n-val breakage.

+1 to merge.

**Comment by coderoshi** [comment]
fwiw, the yz_pb_admin fixes and tests are in a branch off of rz/bugfix/index-n-val (#295). PR pending.

**Comment by rzezeski** [comment]
> fwiw, the yz_pb_admin fixes and tests are in a branch off of rz/bugfix/index-n-val (#295). PR pending.

Ah okay. Thanks.

**Pull request merged**
