### PR TITLE
Add ability to reload indexes

### PR DESCRIPTION
**Pull request by rzezeski**
Add the ability to reload indexes on a running cluster. This is useful
for loading schema changes on the fly. E.g. adding a field to the
schema.

The index reload call is a blocking call that broadcasts cluster-wide.
The caller should always check the return value. If any errors occurred
then the reload should be retried until all nodes report success.
Otherwise you could end up with different version of the schema across
the nodes.

**NOTE:** This PR simply adds the ability to reload indexes on the server. 
It does not add any PB or HTTP support. Thus it only halfway addresses #130.

### CODE REVIEW

**Comment by hazen** [comment]
FWIW:

```
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : fail
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
1 Tests Failed
16 Tests Passed
That's 94.11764705882352% for those keeping score

================ yz_mapreduce failure stack trace =====================
{{badmatch,{ok,"500",
               [{"Server",
                 "MochiWeb/1.1 WebMachine/1.10.5 (jokes are better explained)"},
                {"Date","Mon, 23 Dec 2013 18:58:01 GMT"},
                {"Content-Type","application/json"},
                {"Content-Length","577"}],
               "{\"phase\":0,\"error\":\"bad_json\",\"input\":\"{ok,{r_object,{<<\\\"mr_index\\\">>,<<\\\"b1\\\">>},<<\\
\"key_4\\\">>,[{r_content,{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[[<<\\\"Links\
\\">>]],[],[[<<\\\"dot\\\">>|{<<197,82,177,11,82,184,135,149>>,{1,63555044280}}]],[],[],[],[],[],[[<<\\\"content-type\\\
">>,97,112,112,108,105,99,97,116,105,111,110,47,106,115,111,110],[<<\\\"X-Riak-VTag\\\">>,50,117,119,89,88,55,106,122,77
,109,87,78,78,78,98,118,106,101,114,117,55,78]],[[<<\\\"index\\\">>]],[],[[<<\\\"X-Riak-Last-Modified\\\">>|{1387,825080
,324824}]],[],...}}},...}],...},...}\"}"}},
 [{yz_mapreduce,http_mr,2,[{file,"riak_test/yz_mapreduce.erl"},{line,93}]},
  {yz_mapreduce,'-verify_100_objs_mr/2-fun-2-',2,
                [{file,"riak_test/yz_mapreduce.erl"},{line,63}]},
  {rt,wait_until,3,[{file,"src/rt.erl"},{line,512}]},
  {yz_rt,'-wait_until/2-fun-0-',3,[{file,"riak_test/yz_rt.erl"},{line,358}]},
  {yz_rt,'-wait_until/2-lc$^0/1-0-',2,
         [{file,"riak_test/yz_rt.erl"},{line,358}]},
  {yz_rt,wait_until,2,[{file,"riak_test/yz_rt.erl"},{line,358}]},
  {yz_mapreduce,confirm,0,[{file,"riak_test/yz_mapreduce.erl"},{line,46}]}]}
=======================================================================
```

I've looked at the code and don't see anything egregious.  That said I can't say I understand the system well enough to comment on all of your changes.

**Comment by rzezeski** [comment]
I also see the map-reduce failure. It's a breaking change in Riak KV. Not related to this change.

**Comment by rzezeski** [comment]
Here is the cause of the map-reduce failure: basho/riak_kv#779.

**Comment by coderoshi** [comment]
+1

I had the same MR failure as Brett. I've also been wresting with a `yz_rt:load_data` failure, but doesn't seem to be related to this PR at all.

```
================ yz_rs_migration_test failure stack trace =====================
{{assertEqual_failed,[{module,yz_rs_migration_test},
                      {line,218},
                      {expression,"ExitCode"},
                      {expected,0},
                      {value,126}]},
 [{yz_rs_migration_test,'-load_data/3-fun-0-',2,
                        [{file,"riak_test/yz_rs_migration_test.erl"},
                         {line,218}]},
  {yz_rs_migration_test,load_data,3,
                        [{file,"riak_test/yz_rs_migration_test.erl"},
                         {line,218}]},
  {yz_rs_migration_test,confirm,0,
                        [{file,"riak_test/yz_rs_migration_test.erl"},
                         {line,68}]}]}
===============================================================================
```

**Comment by rzezeski** [comment]
For the load data problem you'll want to look at the console.log for the basho bench run. This shouldn't be related at all. I'm going to go ahead and merge since 3 of us were able to run the tests with fairly consistent results.

**Comment by ghost** [comment]
How does one do this? Calling `rp(yz_index:reload(<<"index_name">>)).` in the console reports success but I still can't query using the new schema. Is there a known sequence of steps to go from a modified schema to querying the data using it?

**Comment by zeeshanlakhani** [comment]
@mtbrooks33, as per my mailing list response

> Remember, with the reload, it’s only new objects in _new_ fields that will take the updates. Depending on how big your dataset is, the quick fix may be to upload the _updated_ schema under a new name and tie the index to that. The K/V pairs should then work correctly when PUT.

**Pull request merged**
