### PR TITLE
Dialyzer fixes (do not merge until riak_core 540 is merged)

### PR DESCRIPTION
**Pull request by bowrocker**
Along with @reiddraper's PR in the parent branch, removes the rest of the dialyzer warnings.

Depends on:
https://github.com/basho/yokozuna/pull/325
https://github.com/basho/riak_core/pull/540

### CODE REVIEW

**Comment by reiddraper** [comment]
Based on the comments on basho/riak_core#539, sounds like I should wait and see what the resolution there is?

**Comment by bowrocker** [comment]
@reiddraper it appears to still work with core PR 540.

**Comment by reiddraper** [comment]
Running dialyzer now, but it's also worth having a domain-expert  (@rzezeski  @coderoshi) to take a look as well.

**Comment by reiddraper** [comment]
I don't see where basho/riak_core#540 exports vclock:sort. Dialyzer complains too.

**Comment by coderoshi** [comment]
oh ha, I was going crazy searching for vclock:sort

**Comment by coderoshi** [comment]
+1 on this, dialyzer is copacetic

**Comment by reiddraper** [comment]
+1 from me too.

**Comment by seancribbs** [comment]
basho/riak_core#540 has been merged.

**Pull request merged**
