### PR TITLE
Don't crash cover on insufficient_vnodes_available

### PR DESCRIPTION
**Pull request by rzezeski**
- Change `calc_plan` to return error-tuple rather than match it and
  throw it.
- Check for error-tuple when generating cached coverage plans and
  store undefined.  That will prevent cover server from crashing.
- Check for error-tuple during search request and return proper error
  msg to user.

### CODE REVIEW

**Comment by rzezeski** [comment]
This addresses #109.

**Comment by coderoshi** [comment]
This change also needs handled on #38.

**Comment by coderoshi** [comment]
+1

**Comment by rzezeski** [comment]
+1, works for me.

**Pull request merged**
