### PR TITLE
hashtree:flush_buffer before finishing build of hashtree

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
simple fix, but make sure to call hashtree:flush_buffer before buildtime, meta for build_finished

^^ @jonmeredith

### CODE REVIEW

**Comment by jonmeredith** [comment]
-1 you have to to do all trees and persist state.

```
diff --git a/src/yz_index_hashtree.erl b/src/yz_index_hashtree.erl
index e966069..28210c7 100644
--- a/src/yz_index_hashtree.erl
+++ b/src/yz_index_hashtree.erl
@@ -370,14 +370,17 @@ apply_tree(Id, Fun, S=#state{trees=Trees}) ->
     end.

 -spec do_build_finished(state()) -> state().
-do_build_finished(S=#state{index=Index, built=_Pid}) ->
+do_build_finished(S=#state{index=Index, built=_Pid, trees=Trees0}) ->
     lager:debug("Finished YZ build: ~p", [Index]),
-    {_,Tree0} = hd(S#state.trees),
+    Trees = orddict:map(fun(_Id, Tree) ->
+                                hashtree:flush_buffer(Tree)
+                        end, Trees0),
+    {_,Tree0} = hd(Trees),
     BuildTime = yz_kv:get_tree_build_time(Tree0),
     hashtree:write_meta(<<"built">>, <<1>>, Tree0),
     hashtree:write_meta(<<"build_time">>, term_to_binary(BuildTime), Tree0),
     yz_kv:update_aae_tree_stats(Index, BuildTime),
-    S#state{built=true, build_time=BuildTime, expired=false}.
+    S#state{built=true, build_time=BuildTime, expired=false, trees=Trees}.

 -spec do_insert({p(),n()}, binary(), binary(), proplist(), state()) -> state().
 do_insert(Id, Key, Hash, Opts, S=#state{trees=Trees}) ->
```

**Comment by zeeshanlakhani** [comment]
@jonmeredith derp on my part... was just looking at https://github.com/basho/yokozuna/blob/32d71135644a579943799ff9a70b67dee0201f80/src/yz_index_hashtree.erl#L526 too. Fixing. orddict:map is cleaner.. but also adding the try/catch.

**Comment by zeeshanlakhani** [comment]
@jonmeredith updated.. on both (sorry for missing that... #dumb)... running aae tests.

**Comment by zeeshanlakhani** [comment]
Don't forget to review w/  https://github.com/basho/riak_kv/pull/1191

**Pull request closed without merging**
