### PR TITLE
Wait up to 20 seconds for yz_index:exists before returning from create/3

### PR DESCRIPTION
**Pull request by drewkerrigan**
This change is in response to #402 (RIAK-1547). Typical wait time for yz_index:exists is between 5-12 seconds. I'm not sure if we should define a new response for cases when it takes longer that 20 seconds to create the index because we can't really be sure if it is just going to take longer or if there was an actual issue with the creation.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@drewkerrigan I was looking at a fix for this too, but I don't feel like a random wait interval works here, and it is not configurable. @seancribbs and I have discussed this and plan to put a little time into a succinct solution, as it seems like sync/blocking-create should be initiated differently. The async one should maybe return that 202 as well if we allow both options, but it seems like being sync is preferable form a http/pb standpoint.

**Comment by drewkerrigan** [comment]
@zeeshanlakhani I agree that the time for a wait interval should be configurable; also agree about returning 202 if we decide to preserve the current async capability, but yes - it seems that a sync/blocking create is the expected behavior from the client perspective anyway. With regard to a different approach, the tricky part about this operation is that the longest part of the operation happens entirely within Solr with little visibility from the Riak side. It would be nice to have a cleaner view of Solr's index creation but it also seems easy to over-engineer that problem. Either way I'm looking forward to getting a fix out for this sooner than later since it comes up a lot for clients.

**Comment by zeeshanlakhani** [comment]
@drewkerrigan yeppers. After doing some thinking, I'm going to implement create as synchronous, keeping compatibility w/ all the apis.

Once I get back onto #130 (RIAK-1173), I'll create specific funs for two-phase commit.

Agree w/ your point on more visibility on the Solr side. I'm hoping the work in Errbal (affiliated w/ #446 (RIAK-1491)) will fit nicely in Yokozuna, and we'll have something better than what we have now. :+1: otherwise.

**Comment by zeeshanlakhani** [comment]
Closing... as the new PR will be up this week.

**Pull request closed without merging**
