### PR TITLE
Merge 2.0->2.1 for hashtree fixes.

### PR DESCRIPTION
**Pull request by JeetKunDoug**
Bad PR - went against develop vs. 2.1

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
Requires basho/riak_core#794 for a clean build.

**Comment by JeetKunDoug** [comment]
@borshop retry

**Comment by JeetKunDoug** [comment]
@borshop: retry

**Comment by zeeshanlakhani** [comment]
:+1: c001bace2014b72060165c26efa716a745c8c875

**Comment by JeetKunDoug** [comment]
Needs to go to 2.1 - recreating the PR

**Pull request closed without merging**
