### PR TITLE
Better index exists.

### PR DESCRIPTION
**Pull request by rzezeski**
Basically, change `yz_index:exists` to check 1) official index list, 2) on-disk and 3) ping if Solr is running. See the commit messages for more detail.

This addresses #249.

There was also a supplementary fix made to the verify script which I broke in a previous commit.There is no longer a top-level `yokozuna` dir in top level working dir. Instead, `riak_yz/deps/yokozuna` is used. You'll need to change your `yz_dir` in the `yz_verify` section of `~/.riak_test.config`.

### CODE REVIEW

**Comment by hazen** [comment]
So far so good:

```
Test Results:
yokozuna_essential-bitcask: pass
```

Next up, the whole suite.

**Comment by hazen** [comment]
```
Test Results:
yz_wm_extract_test-bitcask   : pass
yz_stat_test-bitcask         : pass
yz_solr_start_timeout-bitcask: pass
yz_siblings-bitcask          : pass
yz_security-bitcask          : pass
yz_schema_admin-bitcask      : pass
yz_rs_migration_test-bitcask : pass
yz_pb-bitcask                : pass
yz_monitor_solr-bitcask      : pass
yz_mapreduce-bitcask         : pass
yz_languages-bitcask         : pass
yz_index_admin-bitcask       : pass
yz_fallback-bitcask          : pass
yz_errors-bitcask            : pass
yz_dt_test-bitcask           : pass
yokozuna_essential-bitcask   : pass
aae_test-bitcask             : pass
---------------------------------------------
0 Tests Failed
17 Tests Passed
That's 100.0% for those keeping score
```

**Comment by hazen** [comment]
Not sure how easy it would be to test the degenerate cases where the schema is bad, for example, or a bad ping when Solr is down.

**Comment by rzezeski** [comment]
So the `yz_schema_admin` test already tests bad schemas in the `confirm_bad_schema` test.

I verified this fix by restarting riak nodes after running one of the tests and made sure I didn't see `econnrefused` and other index creation errors anymore.

**Comment by rzezeski** [comment]
@javajolt is that a +1 or would you like to discuss it more?

**Comment by hazen** [comment]
:+1: 

Just curious if we could test these changes programmatically.

**Pull request merged**
