### PR TITLE
cleanup around monitor for sync index proc and refactor flatten/reverse for batchies

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
- monitor process to sync, which calls child process to wait
- refactor reverse/flatten of ops to be closer to ops code

@fadushin testy + looky.

### CODE REVIEW

**Comment by fadushin** [comment]
One thing I'd like to do before +1'ing the list:reverse changes to yz_solrq_helper is to temporarily modify the mapping from vnodes to Solrqs from the existing BKey hash back to the old partition hash, and then uncomment the portions of the EQC test that check for preservation of key ordering-by-vnode, and see if we are still passing EQC with retries.  That would give some confidence that the list_reverse changes in yz_solrq_helper don't affect ordering off retries.  (And also run the EQC test with many iterations).  I can try this, but if anyone else has time, give a holler.

**Comment by zeeshanlakhani** [comment]
The code changes aren't different then what was already on the flush-queues branch btw, just moved closer to ops. But if you want to update the pulse test to check ordering, go for it :).

Zeeshan Lakhani
programmer | 
software engineer at @basho | 
org. member/founder of @papers_we_love | paperswelove.org
twitter => @zeeshanlakhani

**Comment by fadushin** [comment]
Tests pass when reverting hashing strategy, so I confident the retry ordering is not affected by this change.

**Comment by fadushin** [comment]
+1 7f543a3

**Comment by fadushin** [comment]
@borshop merge

**Pull request merged**
