### PR TITLE
Yokozuna fails to re-index the remainder of a partition after a non-indexable document is encountered

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
- update yz_exchange_fsm to catch index error w/ ill-formated/failed document, thank you @kesslerm 
- update aae_test to test for this bug, 
- add a date field to check-up on in fruit_schema.xml

Fixes RIAK-2006 (#525) / https://github.com/basho/yokozuna/issues/525.

Will need to be merged-forward to 2.1 and develop.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@kesslerm very similar to your set of changes... but I added the test and defined it moreso in scope. 

@kesslerm and @fadushin please review and then merge forwarding will commence.

**Comment by zeeshanlakhani** [comment]
@kesslerm i was able to get the failure (forever-waiting for an AAE exchange to occur) just w/ expire and not needing to stop/remove, which makes sense to me.

**Comment by kesslerm** [comment]
@zeeshanlakhani yes expiring trees will have the same effect of AAE exchanges never happening. The code change overcomes the crash, which is the underlying cause, but it still doesn't mark those entries as non indexable. So each time AAE tries to fix the broken entry again, it will be flagged in the logs. At least the rest of the index will be rebuilt fine now.

**Comment by kesslerm** [comment]
:+1: - repeated log entries about non-indexable KV entries are probably a good thing and alert users to the state of their data.

**Comment by zeeshanlakhani** [comment]
@kesslerm right... i was going to mention that. They should be aware, consistently, that this datum is not handled properly. Compared to the previous PR however, I don't have to reshow the trace.

**Comment by kesslerm** [comment]
Cool. Not showing the trace is a nice change. I just tested your version against my test database and it works fine.

**Comment by jadeallenx** [comment]
For whatever its worth (maybe 2 cents)
+1 d09a6ff

**Comment by kesslerm** [comment]
@zeeshanlakhani it would be good to merge this into the relevant branches before the next release cycle. The bug potentially affects many customers. We may also need patched beams for some.

**Comment by zeeshanlakhani** [comment]
@kesslerm yep. that's what we targeted 2.0 first. Then we'll move this forward to 2.1 and develop. It will be def. be in 2.1.2 and eventually 2.0.7.

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Comment by JeetKunDoug** [comment]
:+1: d09a6ff

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Pull request merged**
