### PR TITLE
be more verbose about why yz is stalling kv handoff

### PR DESCRIPTION
**Pull request by jrwest**
otherwise it becomes necessary to ask the operator to run commands via `riak attach` to determine why the handoff is not proceeding.

### CODE REVIEW

**Comment by jrwest** [comment]
see http://riak-users.197444.n3.nabble.com/Issues-with-high-node-load-and-very-slow-response-td4031456.html for more details

**Comment by coderoshi** [comment]
- [x] code review
- [x] compile/unit tests
- [x] r_t
- [x] manual test

**Comment by coderoshi** [comment]
+1 a9fcc31

**Comment by jrwest** [comment]
@borshop merge

**Pull request merged**
