### PR TITLE
fix git repo url

### PR DESCRIPTION
**Pull request by nlf**

### CODE REVIEW

**Comment by rzezeski** [comment]
Actually, the documentation is correct.  However it should probably say "Clone riak" now.  There is no longer a custom branch of Riak needed anymore.

**Comment by nlf** [comment]
Really? All I have to do currently is clone the default branch of riak to get yokozuna?

**Comment by rzezeski** [comment]
Yep.  The default branch of Riak is now `develop`.  If you clone that and run `make` you should see `deps/yokozuna`.

Keep in mind that the develop branch is in a lot of flux ATM.  Chances of a checkout with broken bits around integration are high.  Keep an eye out for dragons.

**Comment by nlf** [comment]
In that case, I'm closing this since it's wrong anyway :)

**Comment by rzezeski** [comment]
Hopefully #208 clarifies things a bit.

**Pull request closed without merging**
